#!/usr/bin/env bash
# All-in-one: install tools, set up the env, train (resumes checkpoints).
# Usage after clone:  bash start.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

FRESH=0
DOWNLOAD=0
GGUF=0
for arg in "$@"; do
  case "$arg" in
    --fresh) FRESH=1 ;;
    --download-checkpoints) DOWNLOAD=1 ;;
    --gguf) GGUF=1 ;;
    -h|--help)
      echo "Usage: bash start.sh [--fresh] [--download-checkpoints] [--gguf]"
      echo "  (default)  hf CLI login, upload JSONL dataset, train, upload adapters + latest checkpoint"
      echo "  --fresh    ignore existing checkpoints and start a new run"
      echo "  --download-checkpoints  pull HF_HUB_REPO (adapters + latest checkpoint) then train"
      echo "  --gguf     after fine-tune: print merge/quantize/upload steps (not run during train)"
      exit 0
      ;;
  esac
done

if [[ "$GGUF" -eq 1 ]]; then
  cat <<'EOF'
GGUF is a follow-up after LoRA training, not part of the default train command.

1. Merge LoRA adapters in ./socratic_finetuned_model into microsoft/Phi-3-mini-4k-instruct (needs extra RAM/VRAM).
2. Convert with llama.cpp convert_hf_to_gguf.py and quantize (e.g. Q4_K_M).
3. Upload gguf/socratic-phi3-q4_k_m.gguf to the same HF_HUB_REPO.

Keep using bash start.sh for train/resume. Add GGUF conversion here later when a college run has finished.
EOF
  exit 0
fi

if [[ -f "$ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env"
  set +a
fi

ensure_uv() {
  if command -v uv >/dev/null 2>&1; then
    return
  fi
  echo "Installing uv..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="${HOME}/.local/bin:${HOME}/.cargo/bin:${PATH}"
  if ! command -v uv >/dev/null 2>&1; then
    echo "uv installed but not on PATH. Open a new terminal or add ~/.local/bin to PATH." >&2
    exit 1
  fi
}

ensure_hf_cli() {
  export PATH="${HOME}/.local/bin:${PATH}"
  if command -v hf >/dev/null 2>&1; then
    return
  fi
  echo "Installing Hugging Face CLI..."
  curl -LsSf https://hf.co/cli/install.sh | bash
  export PATH="${HOME}/.local/bin:${PATH}"
  if ! command -v hf >/dev/null 2>&1; then
    echo "hf CLI not on PATH. Open a new terminal or add ~/.local/bin to PATH." >&2
    exit 1
  fi
}

hf_login() {
  local token="${HF_TOKEN:-${HUGGING_FACE_HUB_TOKEN:-}}"
  if [[ -z "$token" ]]; then
    return
  fi
  echo "Logging in to Hugging Face CLI..."
  hf auth login --token "$token"
}

upload_dataset() {
  local repo="${HF_DATASET_REPO:-Susu11/socraticfinetune}"
  echo "Uploading training JSONL to dataset ${repo} (not the whole folder — that would include .env)..."
  hf repo create "$repo" --repo-type dataset --private --exist-ok 2>/dev/null || true
  hf upload "$repo" "$ROOT/socratic_train.jsonl" --repo-type=dataset
  if [[ -f "$ROOT/socratic_train_data.jsonl" ]]; then
    hf upload "$repo" "$ROOT/socratic_train_data.jsonl" --repo-type=dataset
  fi
}

prompt_hf_once() {
  if [[ ! -t 0 ]]; then
    return
  fi
  export HF_DATASET_REPO="${HF_DATASET_REPO:-Susu11/socraticfinetune}"
  if [[ -z "${HF_HUB_REPO:-}" ]]; then
    read -r -p "Hugging Face MODEL repo (e.g. Susu11/socratic-phi3, Enter to skip weight upload): " HF_HUB_REPO || true
    export HF_HUB_REPO="${HF_HUB_REPO:-}"
  fi
  if [[ -z "${HF_TOKEN:-}" && -z "${HUGGING_FACE_HUB_TOKEN:-}" ]]; then
    read -r -s -p "Hugging Face write token (Enter to skip Hub; input hidden): " HF_TOKEN || true
    echo
    export HF_TOKEN="${HF_TOKEN:-}"
  fi
  if [[ ! -f "$ROOT/.env" ]] && { [[ -n "${HF_HUB_REPO:-}" ]] || [[ -n "${HF_TOKEN:-}" ]]; }; then
    umask 077
    {
      echo "# generated by start.sh — do not commit"
      echo "HF_DATASET_REPO=${HF_DATASET_REPO}"
      echo "HF_HUB_REPO=${HF_HUB_REPO:-}"
      if [[ -n "${HF_TOKEN:-}" ]]; then
        echo "HF_TOKEN=${HF_TOKEN}"
      fi
    } >"$ROOT/.env"
    echo "Saved Hugging Face settings to .env (gitignored). Next time just run: bash start.sh"
  fi
}

ensure_uv
ensure_hf_cli
prompt_hf_once
hf_login

if [[ -n "${HF_TOKEN:-${HUGGING_FACE_HUB_TOKEN:-}}" ]]; then
  upload_dataset
else
  echo "No HF_TOKEN; skipping dataset upload to ${HF_DATASET_REPO:-Susu11/socraticfinetune}."
fi

echo "Installing Python dependencies with uv..."
uv sync

if command -v nvidia-smi >/dev/null 2>&1; then
  if ! uv run python -c "import torch,sys; sys.exit(0 if torch.cuda.is_available() else 1)"; then
    echo "PyTorch has no CUDA. Installing CUDA 12.4 wheel..."
    uv pip install torch --index-url https://download.pytorch.org/whl/cu124
  fi
else
  echo "nvidia-smi not found. Training needs an NVIDIA GPU." >&2
  exit 1
fi

if [[ "$DOWNLOAD" -eq 1 ]]; then
  if [[ -z "${HF_HUB_REPO:-}" ]]; then
    echo "HF_HUB_REPO is empty; cannot download checkpoints." >&2
    exit 1
  fi
  echo "Downloading adapters + latest checkpoint from ${HF_HUB_REPO}..."
  uv run python -c "from huggingface_hub import snapshot_download; snapshot_download(repo_id='${HF_HUB_REPO}', local_dir='${ROOT}/socratic_finetuned_model')"
fi

TRAIN_ARGS=()
if [[ "$FRESH" -eq 1 ]]; then
  TRAIN_ARGS+=(--no-resume)
fi
if [[ -n "${HF_HUB_REPO:-}" ]]; then
  TRAIN_ARGS+=(--push-to-hub "${HF_HUB_REPO}")
fi

echo "Starting training (resumes latest checkpoint unless --fresh)..."
uv run python train.py "${TRAIN_ARGS[@]}"
echo "Done. Adapters/checkpoints are in ./socratic_finetuned_model"
