#!/usr/bin/env bash
# All-in-one: install tools, set up the env, train (resumes checkpoints).
# Usage after clone:  bash start.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

FRESH=0
DOWNLOAD=0
for arg in "$@"; do
  case "$arg" in
    --fresh) FRESH=1 ;;
    --download-checkpoints) DOWNLOAD=1 ;;
    -h|--help)
      echo "Usage: bash start.sh [--fresh] [--download-checkpoints]"
      echo "  (default)  install uv, install deps, train, resume checkpoints, upload if HF is configured"
      echo "  --fresh    ignore existing checkpoints and start a new run"
      echo "  --download-checkpoints  download HF_HUB_REPO into ./socratic_finetuned_model first"
      exit 0
      ;;
  esac
done

if [[ -f "$ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env"
  set +a
fi

ensure_uv() {
  if command -v uv >/dev/null 2>&1; then
    return
  fi
  echo "Installing uv..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="${HOME}/.local/bin:${HOME}/.cargo/bin:${PATH}"
  if ! command -v uv >/dev/null 2>&1; then
    echo "uv installed but not on PATH. Open a new terminal or add ~/.local/bin to PATH." >&2
    exit 1
  fi
}

prompt_hf_once() {
  if [[ ! -t 0 ]]; then
    return
  fi
  if [[ -z "${HF_HUB_REPO:-}" ]]; then
    read -r -p "Hugging Face repo for adapters/checkpoints (e.g. your-user/socratic-phi3-lora, Enter to skip upload): " HF_HUB_REPO || true
    export HF_HUB_REPO="${HF_HUB_REPO:-}"
  fi
  if [[ -z "${HF_TOKEN:-}" && -z "${HUGGING_FACE_HUB_TOKEN:-}" ]]; then
    read -r -s -p "Hugging Face write token (Enter to skip upload; input hidden): " HF_TOKEN || true
    echo
    export HF_TOKEN="${HF_TOKEN:-}"
  fi
  if [[ ! -f "$ROOT/.env" ]] && { [[ -n "${HF_HUB_REPO:-}" ]] || [[ -n "${HF_TOKEN:-}" ]]; }; then
    umask 077
    {
      echo "# generated by start.sh — do not commit"
      echo "HF_HUB_REPO=${HF_HUB_REPO:-}"
      if [[ -n "${HF_TOKEN:-}" ]]; then
        echo "HF_TOKEN=${HF_TOKEN}"
      fi
    } >"$ROOT/.env"
    echo "Saved Hugging Face settings to .env (gitignored). Next time just run: bash start.sh"
  fi
}

ensure_uv
prompt_hf_once

echo "Installing Python dependencies with uv..."
uv sync

if command -v nvidia-smi >/dev/null 2>&1; then
  if ! uv run python -c "import torch,sys; sys.exit(0 if torch.cuda.is_available() else 1)"; then
    echo "PyTorch has no CUDA. Installing CUDA 12.4 wheel..."
    uv pip install torch --index-url https://download.pytorch.org/whl/cu124
  fi
else
  echo "nvidia-smi not found. Training needs an NVIDIA GPU." >&2
  exit 1
fi

if [[ "$DOWNLOAD" -eq 1 ]]; then
  if [[ -z "${HF_HUB_REPO:-}" ]]; then
    echo "HF_HUB_REPO is empty; cannot download checkpoints." >&2
    exit 1
  fi
  echo "Downloading checkpoints from ${HF_HUB_REPO}..."
  uv run python -c "from huggingface_hub import snapshot_download; snapshot_download(repo_id='${HF_HUB_REPO}', local_dir='${ROOT}/socratic_finetuned_model')"
fi

TRAIN_ARGS=()
if [[ "$FRESH" -eq 1 ]]; then
  TRAIN_ARGS+=(--no-resume)
fi
if [[ -n "${HF_HUB_REPO:-}" ]]; then
  TRAIN_ARGS+=(--push-to-hub "${HF_HUB_REPO}")
fi

echo "Starting training (resumes latest checkpoint unless --fresh)..."
uv run python train.py "${TRAIN_ARGS[@]}"
echo "Done. Adapters/checkpoints are in ./socratic_finetuned_model"
