"""Remaining v8 gold stems (unique questions). Packed as 7-tuples."""

from __future__ import annotations


def _p(rows: list[tuple[str, str, str, str, str, str, str]]) -> list[dict[str, str]]:
    keys = ("q", "ask", "hint", "follow", "wrong", "right", "close")
    return [dict(zip(keys, r, strict=True)) for r in rows]


MORE_STEMS: dict[str, list[dict[str, str]]] = {
    "Respiration": _p([
        ("Why do I breathe harder after a sprint?", "What gas is your body trying to get more of to keep muscles working?", "A candle needs a gas to keep burning. Which gas is that, and do working muscles need it too?", "That gas helps release energy from food — so harder breathing means more of it, or less?", "I'm just blowing out carbon dioxide for fun.", "Oxygen.", "That's it — you linked harder breathing to needing more oxygen."),
        ("Why does exhaled air fog limewater?", "What gas that we breathe out can turn limewater milky?", "It's the gas plants take in for photosynthesis. What is it?", "If that gas is a waste of respiration, should there be more of it in inhaled air or exhaled air?", "Limewater detects oxygen.", "Carbon dioxide.", "That's it — exhaled air carries extra carbon dioxide."),
        ("Why can't we live on nitrogen even though air is mostly nitrogen?", "Which gas in air is actually used inside cells to release energy from food?", "About one-fifth of air supports a glowing splint. Which gas is that?", "So is nitrogen the energy-releasing gas, or is it mostly unused filler for us?", "Nitrogen is what we respire.", "Oxygen.", "That's it — cells need oxygen, not nitrogen, to release energy from food."),
        ("Why do yeast make bread rise?", "What gas might yeast produce while they break down sugar without much oxygen?", "Think of fermentation. Which gas puffs the dough?", "Is that the same as breathing oxygen, or a different pathway?", "The yeast eat air holes into the flour.", "Carbon dioxide.", "That's it — yeast fermentation releases CO2 that inflates the dough."),
        ("Why do I feel hot after exercise if respiration is just 'using air'?", "Is energy from food all captured usefully, or is some lost as heat?", "A working engine gets warm. Do muscle cells dump leftover energy as heat too?", "So extra heat after a run — waste of respiration, or proof respiration stopped?", "Exercise creates heat from friction of clothes only.", "Some energy is lost as heat.", "That's it — respiration releases energy, and some of it warms you."),
    ]),
    "Excretion": _p([
        ("What do kidneys actually filter out of blood?", "If cells make chemical waste, which organ is the main filter for that waste in blood?", "You produce urine every day. Which organs make it?", "So kidneys — food storage, or waste and water control?", "Kidneys store extra fat.", "They filter waste from blood.", "That's it — kidneys clean waste from the blood."),
        ("Why is urine not just leftover drinking water?", "Besides water, what dissolved wastes would you expect kidneys to remove?", "Urea comes from breaking down amino acids. Should that stay in blood or leave?", "If urea stayed, would that be healthy or toxic over time?", "Urine is only unused vitamins.", "Wastes like urea dissolved in water.", "That's it — urine carries dissolved wastes, not only extra water."),
        ("Why might someone swell up if their kidneys fail?", "If kidneys also balance water, what happens to extra water that isn't removed?", "A blocked drain leaves a puddle. Where would extra water sit in the body?", "Swelling from extra fluid — kidney job failed, or extra bone growth?", "Failing kidneys make extra blood cells that swell you.", "Extra water stays in the body.", "That's it — kidneys help remove extra water; if they don't, it builds up."),
        ("Why do we sweat on a hot day besides cooling?", "Sweat is water plus a bit of salt. Is that also a way to lose small amounts of waste?", "Two exits for water: urine and sweat. Are both only cooling, or also carrying dissolved bits out?", "So is excretion only urine, or more than one route?", "Sweat is pure water with no dissolved substances.", "A little waste can leave in sweat too.", "That's it — sweat is mainly cooling, but it also carries a little dissolved material out."),
        ("Why is the kidney's nephron a filter and not just a bag?", "What would a filter let through — small dissolved wastes, or whole blood cells?", "Coffee filter: water and tiny bits through, grounds stay. What's the 'grounds' in blood?", "If blood cells stayed in the tubule, would urine look like blood?", "The nephron melts cells into urine on purpose.", "Small dissolved wastes, not whole cells.", "That's it — the nephron filters small wastes and keeps cells in the blood."),
    ]),
    "Reflex action": _p([
        ("Why do I pull my hand back from a hot pan before I 'decide' to?", "Is that decision made after a long think in the brain, or by a quicker path?", "Pain feels slow sometimes, but the hand already moved. Where might the shortcut be?", "Spinal cord shortcut — faster or slower than waiting to ponder?", "I always wait for a full plan from the brain first.", "A quicker path, not a long think.", "That's it — the reflex doesn't wait on a slow conscious decision."),
        ("Why is a knee-jerk useful in a doctor's test?", "Does tapping the tendon send a signal that the spinal cord can answer without you planning a kick?", "You didn't choose to kick. Who 'answered' first — spinal circuit or a written plan?", "If it works, is the reflex arc intact, or must you be concentrating on kicking?", "The doctor magnetizes the knee.", "The spinal cord can answer without a planned kick.", "That's it — the jerk checks a simple reflex pathway."),
        ("Why might a reflex still work if someone is not paying attention?", "Does a reflex require focused thought, or can it run on a built-in circuit?", "You don't study to blink at a sudden poke toward the eye. Thought-heavy, or automatic?", "So attention — required for all movement, or not for this kind?", "All movement needs a speech in your head first.", "It can run on a built-in circuit.", "That's it — reflexes can run without focused attention."),
        ("Why does the pathway skip a long chat with the brain for a burn?", "If waiting for the brain costs time, what could extra time mean for tissue?", "A hot iron. Is a delay of even a fraction of a second free, or expensive?", "So bypassing a long brain loop — protection, or just laziness?", "Burns are imaginary so speed doesn't matter.", "Extra time could mean more damage.", "That's it — a shorter path protects you faster."),
        ("What's the difference between dropping a hot plate as a reflex and choosing to set it down?", "Which one did you plan with awareness, and which snapped first?", "One has a 'I meant to'. The other already happened. Which is the reflex?", "So reflex versus voluntary — timing and awareness, or identical?", "They are the same because both move your arm.", "The snap happened first; putting it down was planned.", "That's it — you separated automatic from chosen movement."),
    ]),
    "Hormones and the endocrine system": _p([
        ("How is a hormone different from a nerve signal?", "Do hormones travel along a wire-like nerve, or through the blood?", "A letter in the post versus a phone call down a cable. Which is more like a hormone?", "So effects — usually slower and longer, or faster and briefer than a reflex?", "Hormones are sparks inside bones only.", "Through the blood.", "That's it — hormones ride the blood, not a single nerve cable."),
        ("What actually controls how tall a person grows?", "Is years-long growth more like a slow chemical message in blood, or a millisecond nerve zap?", "Nerve zaps are quick. Height changes over years. Which timescale fits hormones?", "Growth hormone from a gland — chemical in blood, or an electric thought?", "Height is only from stretching in sleep like taffy.", "A slow chemical message in the blood.", "That's it — long-term growth fits hormones better than a quick nerve zap."),
        ("Why might adrenaline make your heart race before a race?", "Is that a short-term chemical alarm in the blood, or a new bone growing?", "Fight-or-flight. Which gland-ish response is fast-acting in blood?", "Heart racing — adrenaline effect, or digestion speeding up?", "Adrenaline is a vitamin in carrots.", "A short-term chemical alarm in the blood.", "That's it — you tied a rapid body change to a hormone pulse."),
        ("Why don't hormones affect every cell equally?", "Do they fit particular target cells, or soak every cell the same?", "A key and selected locks. What's the lock on a cell?", "So a hormone — broadcast in blood, but answered only where?", "Every cell must respond to every hormone.", "Particular target cells.", "That's it — the message is in blood, the reply is at targets."),
        ("Why is insulin talked about with blood sugar?", "If sugar in blood rises after a meal, what should a hormone do to that level — ignore it, or help cells take it up?", "A thermostat. Too much sugar in blood — signal to store/use it?", "Without that signal, would sugar stay high, or vanish instantly anyway?", "Insulin paints sugar blue.", "Help cells take it up.", "That's it — insulin is about moving sugar out of blood into use/storage."),
    ]),
    "Coordination in plants": _p([
        ("Why does a seedling bend toward a window?", "Is the shoot using nerves like yours, or a chemical that makes one side grow more?", "No brain in a plant. What could make the shaded side elongate?", "More growth on the dark side — bend toward light, or away?", "The plant walks using tiny feet.", "A chemical that makes one side grow more.", "That's it — uneven growth, not animal nerves, turns the shoot toward light."),
        ("Why do roots generally grow down, not up into air?", "Is that a growth response to gravity, or the root looking for sunlight like a leaf?", "Roots in a tipped pot still try a direction. Gravity or gossip?", "Growing down — more about water/minerals and gravity, or catching photons?", "Roots hate oxygen so they flee upward.", "A growth response to gravity.", "That's it — roots are oriented by gravity, not by chasing light like leaves."),
        ("Why might a plant hormone make a fruit ripen together?", "Can a chemical signal spread to nearby fruit, or must each fruit have nerves?", "One ripe banana in a bag. What could it be releasing?", "So ripening — isolated accidents, or a shared chemical cue?", "Fruit ripens only if you shout at it.", "A chemical signal can spread.", "That's it — a hormone-like signal can coordinate ripening."),
        ("A shoot in uniform light grows straight. Why mention auxin at all then?", "If light is even, would auxin stay even, or pile on one side?", "Uneven light causes uneven auxin. Even light?", "Even distribution — straight growth or a hook?", "Auxin only exists at night.", "It would stay more even.", "That's it — the bend needs uneven hormone/growth, not hormone as a magic word only."),
        ("Why don't plants twitch like a reflex when you touch a leaf (except a few)?", "Is most plant coordination slow growth, or instant muscle?", "Watch a sunflower over a day, not a millisecond. Slow or snap?", "So comparing plants to your spinal reflex — same speed, or different?", "All plants kick like knees.", "Most plant coordination is slow growth.", "That's it — plant responses are usually growth over time, not a nerve twitch."),
    ]),
    "Asexual reproduction": _p([
        ("An amoeba splits into two. How many parents were involved?", "Did a partner have to join, or did one cell divide?", "Prefix 'a-' as in without. Without what, in asexual?", "Two identical amoebas — one parent or two?", "It always needs two amoebas to marry first.", "One cell divided — one parent.", "That's it — asexual here means one parent, no partner."),
        ("Why can a potato grow a new plant from a tuber eye?", "Is that a piece of one parent growing, or two plants exchanging pollen?", "No flowers needed for that sprout. Sexual or asexual style?", "The new plant's genes — mix of two, or copy of one?", "The potato must be pollinated by bees in the cupboard.", "A piece of one parent growing.", "That's it — the tuber is asexual: one parent's tissues."),
        ("What's a risk of only cloning a crop asexually?", "If a disease hits one, are the others genetically the same or different?", "Identical copies share the same weaknesses. Safer diversity or not?", "So asexual farming — speed, but what about disease?", "Clones magically never get sick.", "The others are genetically the same.", "That's it — sameness can mean a shared weakness."),
        ("Hydra budding a small hydra on its side — sexual or not?", "Is a gamete fusion happening, or an outgrowth of one body?", "Bud = extra growth. Partner required?", "The bud's genes — mix or copy?", "Budding is two hydras kissing.", "An outgrowth of one body.", "That's it — budding is asexual."),
        ("Why is binary fission a poor plan for oak trees?", "Do large plants usually split their whole body in two, or use other methods?", "An oak is not an amoeba. What would splitting the trunk do?", "So fission — typical for unicellular, or for trees?", "Oaks split down the middle every spring.", "They don't split the whole body in two.", "That's it — binary fission fits tiny single cells, not oak trees."),
    ]),
    "Fertilization": _p([
        ("What has to happen between sperm and egg for a baby to start?", "Does one cell from each join, or do they just sit nearby?", "Half plus half. What do we call the joining?", "The single cell formed — zygote, or a full baby instantly?", "They never meet; bones appear from nowhere.", "One cell from each joins.", "That's it — fertilization is that joining."),
        ("Why isn't the offspring a clone of one parent after fertilization?", "Did genes come from one person or both?", "Half the genome from sperm, half from egg. Mix or copy?", "So traits — only mum, only dad, or a mix?", "The baby is a photocopy of the father.", "Genes from both.", "That's it — both parents contribute genetic material."),
        ("Why do sperm and egg each carry half the usual chromosome number?", "If both kept a full set and fused, would the zygote have a normal set or a double set?", "Meiosis halves. Fusion restores. Why halve first?", "Double set every generation — stable, or a mess?", "They carry triple on purpose.", "The zygote would have a double set.", "That's it — halves fuse back to a normal set."),
        ("Where does fertilization happen in humans, roughly?", "In the ovary as the egg is made, or after the egg is released, in a tube?", "Journey of the egg. Where can sperm meet it?", "So internal meeting place — random skin, or reproductive tract?", "It happens in the stomach.", "After release, in a tube.", "That's it — you placed the meeting in the tract, not the stomach."),
        ("Why must many sperm swim if only one fertilizes?", "Is the journey easy, or do most never arrive?", "Distance, mucus, wrong turns. Why a crowd?", "One winner — others were useless decoration, or a numbers game?", "Only one sperm exists in the body.", "Most never arrive.", "That's it — large numbers offset a hard journey."),
    ]),
    "Puberty and reproductive maturity": _p([
        ("What is puberty, in body terms, not just 'growing up'?", "Are reproductive organs becoming able to play their adult role, or only hair changing?", "Chemical messengers rise. What do we call them?", "Those messengers — nerves only, or hormones too?", "Puberty is when shoes get bigger only.", "Reproductive organs maturing, driven by hormones.", "That's it — you tied puberty to hormones and reproductive maturity."),
        ("Why do bodies change around 11–14 instead of at age 3?", "Is there a hormonal switch that starts later, or did the organs not exist at 3?", "A timer in the endocrine system. Early childhood — same hormone levels as 14?", "So timing — hormone rise, or bones deciding at random?", "Everyone puberties at exactly 3.", "A hormonal switch that starts later.", "That's it — the hormone rise is timed, not random at toddler age."),
        ("Why mention testes and ovaries when talking puberty?", "Which organs start putting out more sex hormones?", "Testosterone and oestrogen — from where?", "Those organs — digestion, or reproduction?", "Hormones come from the kneecaps.", "The reproductive organs.", "That's it — the gonads are central to those hormone changes."),
        ("Why might voice deepen in some teenagers?", "Is that a hormone-driven change in the larynx, or drinking more water?", "Cartilage and folds grow. Chemical push?", "So a body change at puberty — only skin, or other organs too?", "Voices deepen because of extra homework.", "A hormone-driven change in the larynx.", "That's it — you linked a visible change to hormones."),
        ("Is puberty the same as being able to have a child the next day for everyone?", "Does 'starting puberty' equal instant fertility, or is it a process over years?", "First signs versus mature cycles/sperm. Instant or gradual?", "So maturity — a switch flipped in one hour, or a stretch of time?", "The first pimple means instant parenthood always.", "It's a process over years.", "That's it — puberty is a stretch, not one instant."),
    ]),
    "Electric current": _p([
        ("What is actually flowing in a metal wire when a bulb lights?", "Are charges moving through the metal, or is the rubber coating flowing?", "Metal is full of mobile electrons. What moves?", "So current — moving charge, or moving plastic?", "The plastic insulation is the current.", "Charges moving through the metal.", "That's it — current is moving charge in the conductor."),
        ("Why doesn't a bulb light if the circuit is broken?", "Does charge need a closed loop from the source and back, or can it jump a gap easily in a simple battery circuit?", "A broken ring. Can the flow complete?", "Open switch — current, or no current?", "Air is always a perfect wire.", "It needs a closed loop.", "That's it — a complete circuit is required."),
        ("Why is current the same through series bulbs but they can glow differently?", "Is current a pile that gets used up like fuel, or a flow that is the same around a single loop?", "One garden hose loop, same water rate. Fuel tank that empties along the way?", "If current is the same, what might differ — voltage share or current value?", "The last bulb always gets zero current.", "A flow that is the same around the loop.", "That's it — series current is the same; sharing can still differ."),
        ("Conventional current is drawn opposite to electron motion. Does that change the heating of the wire?", "Is heating about charge moving and colliding, or about the arrow's label on the page?", "Electrons one way, arrow the other. Collisions still happen?", "So the label — useful convention, or a different physics of heat?", "If we draw the arrow wrong the wire stays cold.", "Heating is from charge moving and colliding.", "That's it — the convention doesn't cancel the heating."),
        ("Why do we measure current in amperes, not in volts?", "Is an ampere about how much charge passes per second, or about energy per charge?", "Flow rate versus push. Which is current?", "Volts for push, amps for flow — mixed up or matching?", "Amperes measure temperature of the battery.", "How much charge passes per second.", "That's it — current is charge per time."),
    ]),
    "Resistance": _p([
        ("Why do some wires get hot and others don't with similar current?", "Is resistance about opposition to flow, converting some energy to heat?", "Collisions in the metal. More opposition — more heat for that current?", "So a high-R thin wire — hotter or cooler than a thick low-R one, same I?", "Heat comes from the colour of the plastic only.", "Opposition to flow, some energy to heat.", "That's it — you tied resistance to heating."),
        ("Why does a longer wire of the same metal have more resistance?", "Do charges have a longer obstacle course, or a shorter one?", "A longer corridor with the same width. Harder trip?", "Length up, R up or down?", "Longer wire is always a superconductor.", "A longer obstacle course.", "That's it — more length, more resistance."),
        ("Why does warming a metal wire often raise its resistance?", "Do vibrating atoms get in the way more when hotter?", "A crowded dance floor when music gets wilder. Harder to cross?", "Hotter metal — R up or down, typically?", "Heat always turns metal into a perfect conductor.", "Vibrating atoms get in the way more.", "That's it — more vibration, more resistance in typical metals."),
        ("Why is a resistor used in a circuit on purpose?", "Might you want to limit current, or always maximize it?", "A dimmer for an LED. Limit or unleash everything?", "So resistance — only a nuisance, or a tool?", "Resistors exist to make sparks for fun only.", "You might want to limit current.", "That's it — resistance can be a designed limit."),
        ("Two materials, same shape: which has higher resistance, a conductor or an insulator?", "Which lets charge through easily?", "Rubber versus copper. Which opposes flow more?", "Insulator — high R or low R?", "Insulators have zero resistance.", "The insulator opposes flow more.", "That's it — insulators are high resistance."),
    ]),
}
