"""v9 extra intents (foundational + What is X). 10 per concept; last 3 = holdout."""

from gold_v8_more import _p

# last 3 tuples in each list are HOLDOUT (never train)
V9_EXTRA: dict[str, list[dict[str, str]]] = {
    "Pressure and surface area": _p([
        ("What is pressure?", "If you push on a thumbtack, is the effect about force alone, or force spread over how much area?", "Same push on a pin versus a spoon. What changes besides force?", "So is pressure force divided by area, or just a type of energy?", "Pressure is a kind of heat.", "Force spread over area.", "That's it — pressure is how concentrated a force is on an area."),
        ("What do we mean by a small area making a bigger effect?", "Same force, smaller patch — stronger or weaker press?", "Drawing pin. Tiny tip. Stronger effect?", "That's why sharp tools cut — area or magic metal?", "Small area makes force disappear.", "Stronger press on a smaller patch.", "That's it — smaller area, same force, bigger pressure."),
        ("Why does a schoolbag strap feel worse when it is thin?", "Is your bag's weight on a skinny strap spread over less shoulder, or more?", "Thin strap, same books. Pressure up or down?", "Wider strap — more comfortable because of area?", "Thin straps are heavier.", "Less shoulder area, so it presses more.", "That's it — thin strap, smaller area, higher pressure."),
        ("Is pressure the same as force?", "Can two pushes of equal force feel different if one is on a pin?", "Force vs how spread out. Different ideas?", "So we need both force and area to talk pressure?", "Pressure and force are identical words.", "No — pressure also needs area.", "That's it — you unmixed force and pressure."),
        ("What happens to pressure if I keep force the same but double the area?", "Does pressure fall to about half, or stay the same?", "Spread the same push wider. Weaker press?", "P = F/A with A doubled — P down?", "Doubling area doubles pressure.", "Pressure falls (about half).", "That's it — bigger area, smaller pressure if F is fixed."),
        ("Why do ice skates cut ice better than boots?", "Is the blade a tiny area under your weight?", "Same you, thin blade. Pressure?", "High pressure on ice — related to the thin edge?", "Skates are warmer than boots.", "Yes, a tiny area under your weight.", "That's it — blade area is small so pressure is high."),
        ("Can pressure act in fluids as well as on a pin?", "Does a fluid push on the walls of its container?", "Balloon, syringe. Fluid pressure?", "Not only solids poking — liquids and gases too?", "Only pins have pressure.", "Yes — fluids push on surfaces too.", "That's it — pressure is not only sharp solids."),
        ("HOLDOUT: Why does a blunt knife need more push to cut?", "If the edge is wider, is the same force more spread out?", "Wider edge, lower pressure. Need more F to cut?", "Blunt means more area at the edge?", "Blunt knives are magnetized.", "Yes, the force is more spread out.", "That's it — more area, less pressure, so you push harder."),
        ("HOLDOUT: What is a pascal, in school language?", "Is it a unit of pressure, force per area?", "N per m². Name?", "Not a unit of time?", "A pascal is a type of battery.", "A unit of pressure.", "That's it — pascal is a pressure unit."),
        ("HOLDOUT: Why don't I sink into a wooden floor in shoes?", "Is my weight spread over the shoe soles' area?", "Enough area, pressure the wood can take?", "Compared with stiletto heels on soil?", "Floors have no pressure on them.", "Yes — soles spread the weight.", "That's it — enough area keeps pressure manageable."),
    ]),
    "pH scale and neutralization": _p([
        ("What is an alkali?", "Soap is slippery and lemon is sour. Which side is alkali-like?", "Alkalis are soluble bases in water. High pH or low?", "So alkali — soluble base, not any metal?", "Alkali means any acid.", "Soap/high pH — a soluble base.", "That's it — an alkali is a base that dissolves in water."),
        ("What is an acid, in Grade 10 terms?", "Sour lemon — low pH or high?", "Acids in water, H+ idea. Below 7?", "Not the same as alkali?", "Acids are just salty.", "Low pH / sour side, opposite of alkali.", "That's it — acids sit on the low-pH side."),
        ("What does pH 7 mean?", "Is 7 the middle of 0–14, neither strongly acid nor alkali?", "Pure water near 7. Neutral?", "Not the strongest acid?", "pH 7 is the strongest alkali.", "Neutral / middle of the scale.", "That's it — 7 is neutral."),
        ("What is neutralization?", "If acid meets a base, does the mixture move toward 7?", "Ant sting plus baking soda. Toward milder?", "Salt and water often form — that reaction family?", "Neutralization means freezing the liquid.", "Acid + base toward neutral.", "That's it — neutralization is acid meeting base."),
        ("What is a base if it is not soluble?", "Can a base exist that is not called alkali because it barely dissolves?", "Alkali = soluble base. Insoluble base still a base?", "Copper oxide vs NaOH. Language?", "Every base is automatically an alkali.", "A base that doesn't dissolve isn't an alkali.", "That's it — alkali is the soluble kind of base."),
        ("What does a pH less than 7 tell you?", "More acidic than water, or more alkaline?", "3 vs 7. Acid side?", "Smaller number, more acidic character on this scale?", "Below 7 means alkaline.", "More acidic than neutral.", "That's it — pH below 7 is acidic."),
        ("What is the pH scale for?", "Comparing how acidic or alkaline a solution is, 0 to 14?", "A number line for solutions. Purpose?", "Not for measuring mass?", "pH measures temperature.", "How acidic or alkaline a solution is.", "That's it — pH is that acidity/alkalinity scale."),
        ("HOLDOUT: Why is oven cleaner often alkaline?", "Does grease break up better with a soapy high-pH cleaner?", "Alkali vs fat. Cleaning?", "Not because it is a strong acid?", "Oven cleaner is always lemon juice.", "High-pH / alkaline action on grease.", "That's it — many cleaners are alkaline."),
        ("HOLDOUT: What happens to pH if I add lots of water to a strong acid?", "Does it usually move closer to 7, still acid but milder?", "Dilution. Toward 7?", "Not instantly pH 14?", "Dilution makes it more acidic always.", "It gets closer to 7 (milder acid).", "That's it — dilution eases the pH toward 7."),
        ("HOLDOUT: What is a salt in acid–base chemistry?", "A product of neutralization, not only table salt?", "Acid + base → salt + water. Family?", "NaCl is one salt among many?", "Salt means only NaCl from the sea.", "A neutralization product (ionic compound).", "That's it — 'salt' is the product family."),
    ]),
    "Scattering of light and why the sky is blue": _p([
        ("What is light?", "You see the Sun without touching it. What has to travel from the Sun to your eye?", "Cover the window and the room darkens. What did you block?", "Is light travelling brightness from a source, or only paint on objects?", "Light is a type of sound.", "What travels from the source to the eye.", "That's it — light is what travels from a source to your eye."),
        ("What is scattering of light?", "Does some sunlight get sent sideways by air, not only straight from the Sun?", "Blue from the whole sky. Sent aside?", "Not the same as a mirror bounce of one beam only?", "Scattering means the Sun is switched off.", "Light sent sideways by air particles.", "That's it — scattering is light redirected by the air."),
        ("Why is the sky blue and not green in the school story?", "Do shorter blue wavelengths scatter more toward our eyes from all directions?", "Blue vs red scatter. Which more?", "Stay on sky colour, not on sound.", "The sky is painted green at factories.", "Blue is scattered more into our eyes.", "That's it — more blue scatter makes the sky look blue."),
        ("What is sunlight made of, for this topic?", "Is it a mix of colours, even if it looks white?", "Prism later. Mix inside white?", "Not a single yellow paint?", "Sunlight is only red.", "A mix of colours that looks white.", "That's it — white sunlight is a mix."),
        ("Why look at the sky beside the Sun, not only at the Sun's disk?", "Is the blue coming from scattered light from the air all around?", "Sideways scatter. Whole dome?", "Disk is the source; sky is scatter?", "The sky is a second sun.", "Blue from air all around, not only the disk.", "That's it — you separated the disk from the scattered sky."),
        ("What would the sky look like with no air?", "Black, because nothing scatters sunlight to your side?", "Moon daytime sky. No air?", "Atmosphere needed for blue?", "No air would make a brighter blue.", "Black / space-like, no scatter.", "That's it — no air, no blue sky."),
        ("Is a blue wall the same physics as a blue sky?", "Is wall colour mostly pigments reflecting, while sky blue is scatter in air?", "Paint vs air. Different?", "Don't treat them as identical.", "Blue walls are pieces of sky stuck on.", "No — paint vs scattering in air.", "That's it — you unmixed paint and sky scatter."),
        ("HOLDOUT: Why can distant hills look bluish?", "Is extra air in the way scattering blue toward you?", "More air path. Haze?", "Related to sky scatter, still light, not sound?", "Hills are actually blue rock.", "More air scattering blue at you.", "That's it — air in the path adds blue haze."),
        ("HOLDOUT: What is a wavelength, in one careful step?", "Is it a way to tell colours of light apart in this topic?", "Blue shorter than red in the school picture. Wavelength?", "Stay on light colours.", "Wavelength is a type of mass.", "A way to distinguish colours of light.", "That's it — different colours, different wavelengths."),
        ("HOLDOUT: Does smoke make the same blue sky?", "Big smoke droplets can scatter differently than tiny air molecules — still about light, not sound?", "Size of scatterer. Sky vs smoke?", "Don't jump to sound waves.", "Smoke is how the sky is made every day.", "Smoke scatter isn't the same as clear-air blue.", "That's it — molecule scatter vs smoke is different."),
    ]),
    "Food chains and energy flow": _p([
        ("What is energy?", "When you lift a book, you can get something back if it falls. Is energy a stored ability to cause change, or a type of animal?", "Food and running. Ability to do things. Energy?", "Stay on energy, not on light or sound unless they bring it up.", "Energy is a vitamin in packets.", "The ability to cause change / do work.", "That's it — energy is that capacity to cause change."),
        ("What is a food chain?", "Who eats whom, starting from a plant?", "Grass → deer → tiger. A line of eating?", "Not a metal chain in a factory?", "A food chain is a type of molecule.", "A who-eats-whom line from a producer.", "That's it — a food chain is that feeding sequence."),
        ("What is a producer?", "Who makes food from sunlight in the meadow?", "Grass. Autotroph?", "Not the tiger?", "Producers are the top predators.", "The plants that make the food.", "That's it — producers make the food."),
        ("What is a consumer?", "Who must eat another organism for energy?", "Deer, tiger. Heterotroph?", "Opposite of producer?", "Consumers make sunlight.", "An eater, not a food-maker.", "That's it — consumers eat others."),
        ("Why is energy lost along the chain?", "Do life processes dump much of it as heat?", "Leaking bucket. 10% idea?", "Less at the top — energy reason?", "Energy grows at each step.", "Much is lost as heat in life processes.", "That's it — losses mean less energy higher up."),
        ("What is a trophic level?", "A feeding step: plants, then herbivores, then carnivores?", "Level in the chain. Name?", "Not a type of soil?", "Trophic means magnetic.", "A feeding step in the chain.", "That's it — trophic level is the feeding step."),
        ("What is a food web?", "Many linked chains, not one straight line?", "Real ecosystems. Web?", "More realistic than one chain?", "A web is a spider only.", "Many linked feeding paths.", "That's it — a web is connected chains."),
        ("HOLDOUT: What is an herbivore in this chain?", "A consumer that eats plants?", "Deer. Plant-eater?", "Not a sunlight-maker?", "Herbivores eat only tigers.", "A plant-eating consumer.", "That's it — herbivore eats plants."),
        ("HOLDOUT: Where is most energy stored at the start?", "In the producers / biomass of plants?", "Base of the pyramid. Plants?", "Not in the few tigers?", "Most energy is in the top predator.", "In the plants at the base.", "That's it — most energy starts in producers."),
        ("HOLDOUT: What is heat doing in this energy story?", "Is it energy leaving the chain that animals can't reuse as food?", "Lost to surroundings. Heat?", "That's why the chain can't be endless?", "Heat adds extra food at each step.", "Heat is energy lost from the chain.", "That's it — heat is the leak."),
    ]),
}
