"""More v9 extras."""

from v9_extra_rest import add

add("Oxidation and corrosion", [
    ("What is oxidation, school-level here?", "Often gaining oxygen / losing electrons in the later picture?", "Rusting iron. Oxygen adding?", "Stay on this topic.", "Oxidation is a type of plant.", "Gaining oxygen (or the electron story).", "That's it — oxidation is that oxygen/electron change."),
    ("What is rust, chemically loosely?", "Hydrated iron oxide from iron + air/water?", "Red-brown on steel. What formed?", "Stay on corrosion.", "Rust is a type of current.", "Iron oxide from corrosion.", "That's it — rust is corroded iron oxide."),
    ("What is corrosion?", "The unwanted oxidation of a metal in the environment?", "Statues, cars. Eating away?", "Not a type of light?", "Corrosion is photosynthesis.", "Unwanted attack of metal by the environment.", "That's it — corrosion is that attack."),
    ("What does iron need to rust easily in school demos?", "Air (oxygen) and water?", "Dry vs wet nails. Both?", "Not darkness as the chemical?", "Iron rusts only in pure nitrogen.", "Oxygen and water.", "That's it — air and water."),
    ("How can we slow rust?", "Paint, oil, galvanising — keep air/water off or a more reactive coat?", "Barrier. Prevention?", "Stay on iron.", "Rust is stopped by shouting.", "A barrier or a sacrificial/more reactive coat.", "That's it — keep the iron from air and water, or protect it."),
    ("What is galvanising?", "Coating iron with zinc?", "Dustbin steel. Zinc coat?", "Sacrificial idea later?", "Galvanising is painting with chlorophyll.", "A zinc coat on iron.", "That's it — galvanising is zinc on iron."),
    ("Is tarnish on silver the same word family?", "Also a surface corrosion/oxidation, different metal?", "Blackening. Still corrosion family?", "Not identical to red rust?", "Silver rusts into iron oxide.", "A related surface attack, not iron rust.", "That's it — tarnish is a cousin, not iron rust."),
    ("Does gold rust like iron?", "Usually no — too unreactive?", "Jewellery. Lasting shine?", "Reactivity?", "Gold rusts overnight in air.", "Typically it doesn't rust like iron.", "That's it — gold resists that corrosion."),
    ("Is rusting a redox idea?", "Iron is oxidised; oxygen is involved — later, electron transfer?", "Two sides. Redox?", "Grade 10 can say oxidation of iron?", "Rusting is a type of sound wave.", "Yes — iron is oxidised.", "That's it — rusting oxidises the iron."),
    ("Why rust weakens a structure?", "Metal is converted to flaky oxide, less strong iron left?", "Flakes off. Strength?", "Not because rust is magnetic glue?", "Rust makes iron stronger always.", "You lose solid metal to crumbly oxide.", "That's it — oxide isn't the original strength."),
])

add("Types of chemical reactions", [
    ("What is a combination reaction?", "Two or more substances making one product?", "A + B → AB. Join?", "Stay on types.", "Combination means splitting always.", "Joining into one product.", "That's it — combination is joining."),
    ("What is a decomposition?", "One substance splitting into more than one?", "AB → A + B. Split?", "Opposite of combination?", "Decomposition is only melting ice as a new element.", "One splits into more.", "That's it — decomposition is splitting."),
    ("What is displacement?", "A more reactive element pushing a less reactive one out of a compound?", "Zn in copper sulfate. Swap?", "Stay on this.", "Displacement is a type of light.", "A more reactive element replacing a less reactive one.", "That's it — that's displacement."),
    ("What is double displacement?", "Ions swapping partners, often a precipitate?", "Two solutions. Swap partners?", "Not a type of plant?", "It means two magnets dancing.", "Ions exchanging partners.", "That's it — double displacement is the partner swap."),
    ("What is a precipitation reaction, loosely?", "An insoluble solid appears from mixing solutions?", "Cloudy / solid falling. Precipitate?", "Often a double displacement?", "Precipitate means rain in the beaker of weather only.", "An insoluble solid forms.", "That's it — precipitate is the new solid."),
    ("What is a redox reaction in school language?", "Oxidation and reduction together?", "Rust, combustion. Both sides?", "Not only acids?", "Redox is a type of hormone.", "Oxidation plus reduction.", "That's it — redox is both together."),
    ("Can combustion be typed as combination too?", "Often fuel + oxygen combining, and also redox/exo?", "Overlapping labels. Possible?", "Don't fight over one exclusive box?", "Combustion cannot be classified.", "Yes — more than one label can fit.", "That's it — types can overlap."),
    ("Why classify reactions at all?", "So you can predict products from a pattern?", "Pattern recognition. Why bother?", "Exam and lab planning?", "Classification is only for art class.", "Patterns help you predict.", "That's it — types are prediction tools."),
    ("Is dissolving salt always a chemical type here?", "Often taught as physical; new substance isn't the point?", "Unmix physical vs chemical?", "Stay on reaction types.", "Dissolving always makes a new element.", "Usually a physical change, not these chemical types.", "That's it — dissolving isn't those reaction types."),
    ("What is a neutralization as a type?", "Acid + base, a kind of double displacement toward salt + water?", "pH chapter meets types. Fit?", "Still a chemical reaction?", "Neutralization is a type of current.", "Acid plus base to salt and water.", "That's it — neutralization sits with those types."),
])

add("Soap and detergent cleansing action", [
    ("How does soap clean grease, school picture?", "A molecule with a water-loving and a grease-loving part, lifting oil into water?", "Two ends. Micelle story loosely?", "Stay on cleaning, not on sound.", "Soap eats grease with teeth.", "One end in water, one in grease, so oil can wash away.", "That's it — two-ended molecules lift grease."),
    ("What is hard water's problem with soap?", "It can make scum instead of a good lather?", "Calcium ions. Scum?", "Detergents often still work?", "Hard water is frozen soap.", "Ions that spoil soap lather / make scum.", "That's it — hardness interferes with soap."),
    ("What is scum?", "An insoluble product of soap with hardness ions?", "Grey bits. Scum?", "Not the dirt you wanted to lift?", "Scum is a type of light.", "Insoluble soap-hardness product.", "That's it — scum is that insoluble product."),
    ("Why can detergents work better in hard water?", "They don't form that same scum as readily?", "Still clean. Detergent vs soap?", "Stay on this.", "Detergents are soaps made of metal.", "They lather/clean despite hardness better.", "That's it — detergents cope with hardness better."),
    ("Is soap a salt of a fatty acid, loosely?", "Yes in the school organic chapter?", "From oils/fats + alkali. Soap?", "Stay on carbon compounds / cleaning.", "Soap is sodium metal chunks.", "A salt from fats/oils and alkali.", "That's it — soap from fat plus alkali."),
    ("What does hydrophilic mean here?", "Water-loving end of the soap ion?", "Heads in water. Hydrophilic?", "Opposite of the grease tail?", "Hydrophilic means afraid of water.", "The water-loving part.", "That's it — hydrophilic loves water."),
    ("What does hydrophobic mean here?", "Water-hating / grease-loving tail?", "Tails in oil. Hydrophobic?", "Stay on the two ends.", "Hydrophobic means loves water only.", "The grease-loving part.", "That's it — hydrophobic hides in grease."),
    ("What is a micelle, loosely?", "Soap ions around an oil droplet, greasy tails in, heads out?", "Tiny ball in wash water. Micelle?", "That's how grease stays suspended?", "A micelle is a type of cell in the brain.", "A cluster that traps oil in water.", "That's it — micelle is the oil-trapping cluster."),
    ("Does soap kill germs as its main Grade-10 story?", "The chapter is about lifting grease/dirt; hygiene is extra?", "Cleansing action. Main idea?", "Don't overclaim medicine?", "Soap's only job is electricity.", "The science story is lifting grease into water.", "That's it — cleansing is the grease-lift."),
    ("Why rinse after soaping?", "To wash away the oil-soap clusters with water?", "Rinse. Carry off?", "Not because soap must stay forever?", "Rinsing adds more grease.", "Water carries the lifted dirt away.", "That's it — rinse removes what soap lifted."),
])

add("Modern periodic law and atomic number", [
    ("What is atomic number?", "The number of protons in the nucleus?", "Z. Identity of the element?", "Not the mass number?", "Atomic number is the boiling point.", "The proton count.", "That's it — atomic number is protons."),
    ("What does the modern periodic law say?", "Properties repeat when elements are arranged by atomic number?", "Mendeleev used mass; modern uses Z. Law?", "Stay on the table.", "It says elements are random stickers.", "Periodic properties by atomic number.", "That's it — arranged by Z, properties repeat."),
    ("Why not arrange by mass number now?", "Atomic number is the clearer identity; some mass order swapped?", "Isotopes later. Z vs mass?", "Modern table uses Z?", "Mass number is always the best only key.", "Z is the identity key.", "That's it — we key the table on Z."),
    ("What is a period?", "A horizontal row?", "Left to right. Period?", "Not a full stop only?", "A period is a vertical family.", "A row of the table.", "That's it — period means a row."),
    ("What is a group?", "A vertical column of similar elements?", "Family. Group?", "Alkali metals as an example?", "A group is a row.", "A column / family.", "That's it — group means a column."),
    ("Why do group members act alike, loosely?", "Same number of outer electrons in the school picture?", "Valence. Similar chemistry?", "Stay on this.", "They act alike because they are the same colour.", "Same outer-electron pattern.", "That's it — similar outer electrons, similar chemistry."),
    ("What are isotopes, in one line?", "Same atomic number, different mass number / neutrons?", "Same element, different mass. Isotope?", "Don't mix with groups?", "Isotopes are different elements entirely.", "Same Z, different neutrons.", "That's it — isotopes share Z, not neutron count."),
    ("Who gets credit for atomic-number order in school stories?", "Moseley associated X-rays with Z?", "After Mendeleev. Moseley?", "Modern law?", "Newton invented the periodic table.", "Moseley's atomic-number work.", "That's it — Z became the order."),
    ("Does atomic number equal electrons in a neutral atom?", "Yes — protons equal electrons when uncharged?", "Neutral carbon 6 and 6. Match?", "Ions differ?", "Neutral atoms have no electrons.", "Yes, in a neutral atom.", "That's it — neutral means electrons = Z."),
    ("Is mass number the same as atomic number?", "No — mass number is protons plus neutrons?", "A vs Z. Unmix?", "Stay on this.", "They are identical.", "No — A is p + n; Z is p.", "That's it — you unmixed A and Z."),
])

add("Periodic trends in groups", [
    ("What happens to reactivity down Group 1, school story?", "Alkali metals get more reactive down the group?", "Sodium vs potassium in water. Who more lively?", "Stay on groups.", "They get less reactive forever down the group.", "Reactivity increases down Group 1.", "That's it — down Group 1, more reactive."),
    ("What happens to reactivity down Group 17, school story?", "Halogens often get less reactive down the group?", "Fluorine vs iodine. Who keener?", "Opposite-ish of Group 1?", "Halogens get more reactive down always like Group 1.", "Reactivity tends to fall down the halogens.", "That's it — down Group 17, often less reactive."),
    ("What is an alkali metal?", "Group 1 metal: Li, Na, K…?", "Soft, react with water. Family?", "Not a halogen?", "Alkali metals are noble gases.", "A Group 1 metal.", "That's it — alkali metal is Group 1."),
    ("What is a halogen?", "Group 17: F, Cl, Br, I…?", "Salt-formers. Family?", "Not Group 1?", "Halogens are only metals.", "A Group 17 element.", "That's it — halogen is Group 17."),
    ("Why does atomic size often increase down a group?", "More shells / energy levels?", "Extra layer. Bigger atom?", "Stay on trends.", "Atoms shrink to nothing down a group.", "More electron shells, larger atoms.", "That's it — extra shells, bigger atoms."),
    ("What is a noble gas, in this chapter?", "Group 18, very unreactive, full outer shell story?", "Helium, neon. Unreactive?", "Not alkali metals?", "Noble gases explode in water like potassium.", "An unreactive Group 18 element.", "That's it — noble gases are the unreactive family."),
    ("Do metals and non-metals sit randomly?", "Metals toward the left, non-metals toward the right, school map?", "Staircase. Places?", "Stay on the table.", "Metals are only on the far right always.", "Left metallic, right non-metallic, roughly.", "That's it — that's the school map."),
    ("What is metallic character down a group, loosely?", "Often increases down for the left groups in school talk?", "Easier to lose electrons, bigger atoms. Metal-like?", "Don't over-quantify?", "Metallic character is a type of sound.", "More metallic down some groups in the school story.", "That's it — down-group metallic character can rise."),
    ("Why compare only within a group for these trends?", "Same outer-electron count, changing size/shells?", "Fair family comparison. Why group?", "Across a period is a different trend set?", "Groups are unrelated stickers.", "A group is one family with a changing size.", "That's it — trends need a fair family."),
    ("Is potassium more reactive than sodium with water?", "Yes in the usual demo story?", "Group 1 down. K vs Na?", "Stay on this trend.", "Sodium is always livelier than potassium.", "Potassium is more reactive.", "That's it — K outruns Na in that demo."),
])

add("Basis of five-kingdom classification", [
    ("What is classification for?", "Grouping organisms so we can study and name them consistently?", "Not random piles. Purpose?", "Stay on biology.", "Classification is a type of current.", "Putting organisms into useful groups.", "That's it — classification organises living things."),
    ("What is a kingdom in five-kingdom?", "A very large group: Monera, Protista, Fungi, Plantae, Animalia?", "Top boxes. Kingdom?", "Whittaker's five?", "A kingdom is a type of molecule.", "A top-level group in that system.", "That's it — kingdom is the top box."),
    ("What is Monera, school-level?", "Prokaryotes / bacteria-like, no true nucleus?", "No nucleus. Monera?", "Not plants with flowers?", "Monera are only tigers.", "The prokaryote kingdom.", "That's it — Monera are prokaryotes."),
    ("What is a prokaryote?", "A cell without a true nucleus?", "Bacteria. No nuclear membrane?", "Opposite of your cells?", "Prokaryotes are only plants.", "No true nucleus.", "That's it — prokaryote means no true nucleus."),
    ("Why are fungi not plants in this system?", "They don't photosynthesise like plants; they absorb food?", "Mushrooms. Heterotrophs?", "Stay on five-kingdom.", "Fungi are green plants with flowers.", "Different nutrition from plants.", "That's it — fungi aren't plants here."),
    ("What is Protista, loosely?", "Mostly unicellular eukaryotes in the school box?", "Amoeba, some algae. Catch-all?", "Have a nucleus?", "Protista are only viruses as animals.", "Mostly unicellular eukaryotes.", "That's it — Protista is that box."),
    ("What is a eukaryote?", "A cell with a true nucleus?", "You, plants, fungi. Nucleus?", "Opposite of Monera?", "Eukaryotes have no DNA.", "True nucleus present.", "That's it — eukaryote means true nucleus."),
    ("Why five, not two (plant/animal) only?", "Too many don't fit plant vs animal — bacteria, fungi, protists?", "Old two-kingdom problems. Why expand?", "Stay on this.", "Everything is only plant or animal.", "Two boxes weren't enough.", "That's it — five boxes fit better."),
    ("Are viruses a kingdom here?", "Usually not — they sit outside this living-kingdom scheme in school?", "Acellular. Not a kingdom?", "Don't force them into Monera?", "Viruses are plants.", "Typically not a fifth/sixth living kingdom here.", "That's it — viruses aren't a kingdom in this scheme."),
    ("What features are used to split kingdoms?", "Cell type, body organisation, nutrition mode, in the school list?", "Nucleus, uni/multi, auto/hetero. Criteria?", "Not favourite colour?", "We classify by shoe size only.", "Cell type, organisation, nutrition.", "That's it — those are the school criteria."),
])
