"""More v9 extras."""

from v9_extra_rest import add

add("Reactivity series and displacement reactions", [
    ("What is the reactivity series?", "A league table of metals by how readily they react?", "K at the top, Au low. Order?", "Stay on metals.", "It is a food chain of animals.", "Metals ordered by reactivity.", "That's it — that's the reactivity series."),
    ("What is a displacement reaction here?", "A more reactive metal pushing a less reactive one out of a compound/solution?", "Zn in CuSO4. Copper appears?", "Stay on this.", "Displacement is a type of wave.", "More reactive metal replaces a less reactive one.", "That's it — that's displacement."),
    ("Will copper displace zinc from zinc sulfate, school expectation?", "No — copper is less reactive than zinc?", "Wrong way. Happen?", "Series as a predictor?", "Copper always displaces everything.", "No — copper is too low.", "That's it — the series forbids that way."),
    ("Why does zinc coat with copper in CuSO4?", "Zinc is more reactive, so it displaces Cu2+ to copper metal?", "Blue solution fades. Why?", "Stay on this.", "The zinc paints itself for fun.", "Zinc displaces copper from solution.", "That's it — Zn in, Cu out."),
    ("Where is hydrogen in the series used?", "Metals above H can displace it from acids, below generally don't?", "Mg vs Cu in acid. Fizz?", "Link to acid + metal?", "Hydrogen is a metal at the top always.", "Above H fizz in acid; below usually don't.", "That's it — H is the acid-fizz line."),
    ("Is gold at the top of the series?", "No — it's unreactive, at the bottom in the school list?", "Jewellery lasting. Low?", "Opposite of potassium?", "Gold is the most reactive metal.", "Gold is low / unreactive.", "That's it — gold sits low."),
    ("What does 'more reactive' mean for displacement?", "More tendency to form ions / leave as a compound, pushing the other to metal?", "Who becomes ions. Tendency?", "Don't need full electrochem?", "More reactive means heavier always.", "It more readily displaces the other.", "That's it — more reactive displaces."),
    ("Can carbon or hydrogen appear in extraction stories?", "Yes — a more reactive 'reducer' can pull a metal from its ore in school?", "Extraction. Related series idea?", "Stay Grade 10.", "Carbon never appears in metal work.", "Reactivity ideas also guide extraction.", "That's it — the series helps extraction talk."),
    ("Why potassium isn't stored in CuSO4 demos?", "Too reactive — violent, not a calm displacement class demo?", "Safety. K vs Zn?", "Use zinc for school displacement?", "Potassium is safer than zinc in solutions.", "Too reactive for that demo.", "That's it — pick a moderate metal for class."),
    ("Is the series about non-metals' pH?", "No — it's metals (and H) vs how they react?", "Unmix with acids chapter slightly, keep metals?", "Stay on this.", "The series is the pH scale.", "It's a metal reactivity order.", "That's it — metal league table, not pH."),
])

add("Newton's first law (inertia)", [
    ("What is Newton's first law, in student words?", "If no net force, velocity stays the same — rest stays rest, uniform motion stays uniform?", "Ice-hockey puck. Keep going?", "Stay on this law.", "The first law says force is a type of acid.", "No net force, motion doesn't change.", "That's it — that's the first law."),
    ("What is inertia?", "The tendency to keep the current motion (including rest)?", "Passengers lurch. Keep going?", "Mass as a measure later?", "Inertia is a type of current.", "Tendency to keep doing what it's doing.", "That's it — inertia is that stubbornness of motion."),
    ("Why do you lurch forward when a bus stops?", "Your body wants to keep moving; the bus slowed?", "First law. You vs bus?", "Not a forward force magically appearing?", "A force pulls you forward from the air.", "You keep moving while the bus slows.", "That's it — you continued; the bus didn't."),
    ("Why a book stays on the table?", "Net force is zero: gravity and the table's push cancel, so it stays at rest?", "Balanced forces. Stay put?", "Not because gravity switched off?", "Books hover from magnetism.", "Balanced forces, so it stays at rest.", "That's it — zero net force, stays put."),
    ("Does 'no force' mean 'must be at rest'?", "No — it could move at constant speed in a straight line?", "Space puck. Uniform motion?", "That's the law's second half?", "Moving things must have a net force always.", "Constant velocity is also allowed.", "That's it — rest or steady straight motion."),
    ("Why seatbelts, in first-law language?", "You keep moving in a crash; the belt applies force to slow you with the car?", "Inertia. Belt?", "Stay on this, not on design details?", "Seatbelts push the car faster.", "They provide the force to change your motion with the car.", "That's it — the belt counters your inertia."),
    ("If friction vanished on a road, what about a rolling ball?", "It would keep going (until something else acts)?", "Ideal ice. Keep rolling?", "That's first law?", "It must stop because motion is illegal.", "It would keep going.", "That's it — without a stopping force, it continues."),
    ("Is inertia a force?", "No — it's a property of mass, not a push?", "Don't invent an 'inertia force' as the cause?", "Unmix?", "Inertia is a type of pull from the Earth always.", "It's a property, not a force.", "That's it — inertia isn't a force."),
    ("What is net force here?", "The leftover after all pushes/pulls are combined?", "Unbalanced. Net?", "Zero net ↔ first law case?", "Net force is the colour of the object.", "The overall unbalanced push.", "That's it — net is the leftover force."),
    ("Why is a spaceship's coasting not 'needing an engine always' in the law?", "No air drag in empty space, so it can keep velocity?", "Engines to change velocity, not to 'keep existence of motion'?", "Stay on first law.", "Engines must run or motion vanishes by law.", "Without drag, motion can persist.", "That's it — empty space has no drag to kill velocity."),
])

add("Newton's third law (action-reaction)", [
    ("What is Newton's third law?", "Forces come in pairs: A on B, B on A, equal size, opposite direction?", "You push wall, wall pushes you. Pair?", "Stay on this law.", "The third law is about pH.", "Equal and opposite force pairs.", "That's it — that's the third law."),
    ("If I push a friend, who gets a force?", "Both — you on them and they on you?", "Ice, both slide. Both?", "Not only the friend?", "Only the friend ever feels a force.", "Both of you.", "That's it — both get a force."),
    ("Do the two forces act on the same object?", "No — each on a different object?", "That's why they don't cancel on one free-body?", "Unmix with first-law net force?", "Both forces sit on one person only.", "They act on two different bodies.", "That's it — two bodies, two forces."),
    ("Why can I walk?", "You push the ground backward; the ground pushes you forward?", "Feet vs Earth. Pair?", "Stay on walking.", "Walking is a type of magnet pulling you.", "Ground's forward push on you.", "That's it — the ground pushes you forward."),
    ("If the forces are equal, why does a fly not smash a bus?", "Same size forces, but the bus's motion barely changes because of mass?", "Equal force ≠ equal acceleration. Mass?", "Don't deny the pair?", "The fly's force is infinite.", "Equal forces, very different mass effects.", "That's it — equal force, unequal effect if masses differ."),
    ("Is the pair 'action then later reaction'?", "They happen together, not a delayed revenge?", "Simultaneous. Together?", "Stay on this.", "Reaction waits a minute.", "They are simultaneous.", "That's it — together, not later."),
    ("Rocket gases go back; why does the rocket go forward?", "Gas pushed back, gas pushes rocket forward?", "Third law. Exhaust?", "Stay on this, not on burning chemistry?", "Rockets need air to push on.", "The gas pushes the rocket the other way.", "That's it — exhaust back, rocket forward."),
    ("Can a force exist alone without a partner?", "The third law says no — always a pair?", "One-sided force. Allowed?", "Stay on this.", "Lone forces are common.", "No lone forces in this law.", "That's it — always a pair."),
    ("If two forces are equal and opposite on me, is that third law?", "Only if they are on two different objects; on me they might be a first-law balance?", "Cancel on one body vs pair across two. Unmix the laws?", "Stay careful?", "Any two arrows are third law.", "Third-law partners live on two bodies.", "That's it — you unmixed balanced forces and third-law pairs."),
    ("Why a gun recoils?", "Bullet forward, gun backward — pair?", "Kick. Recoil?", "Stay on third law.", "The gun is magnetic only.", "The bullet's push has a backward partner on the gun.", "That's it — recoil is the partner force."),
])

add("Biodegradable vs non-biodegradable waste", [
    ("What is biodegradable waste?", "Material microbes can break down in a reasonable time?", "Peel, paper. Rot?", "Stay on this.", "Biodegradable means made of metal only.", "Waste living things can decompose.", "That's it — biodegradable can rot."),
    ("What is non-biodegradable waste?", "Material that doesn't break down that way for a very long time?", "Many plastics. Persist?", "Stay on this.", "Non-biodegradable means it vanishes in an hour.", "Waste that doesn't decompose readily.", "That's it — it persists."),
    ("Why is plastic a problem in this chapter?", "Much of it is non-biodegradable, so it piles up?", "Litter lasting. Plastic?", "Stay on waste, not on sound.", "Plastic is a vitamin that plants eat instantly.", "It stays in the environment.", "That's it — lasting plastic is the problem."),
    ("Can biodegradable still be a problem?", "Yes if dumped wrongly — smell, water pollution, methane in dumps?", "Rotting heaps. Still care?", "Not 'always harmless'?", "Biodegradable is always harmless everywhere.", "Yes — disposal still matters.", "That's it — biodegradable isn't automatically harmless."),
    ("What is composting, loosely?", "Letting biodegradable waste break down into useful humus-like material?", "Kitchen scraps. Compost?", "Stay on this.", "Composting is melting plastic into gold.", "Controlled rotting of bio-waste.", "That's it — composting is managed breakdown."),
    ("Why reduce, reuse, recycle as a slogan here?", "Less waste generated and less lasting rubbish?", "Three R's. Point?", "Especially for non-bio?", "The slogan is about Newton's laws.", "Cut waste and keep materials in use.", "That's it — less lasting rubbish."),
    ("Is glass biodegradable?", "No — it persists, though it can be recycled?", "Bottles lasting. Glass?", "Unmix recycle vs biodegrade?", "Glass rots like banana peels.", "Glass isn't biodegradable; it can be recycled.", "That's it — persist vs recycle."),
    ("What do microbes do to biodegradable stuff?", "They eat/break the molecules as food, turning it into simpler substances?", "Decomposers. Job?", "Stay on this.", "Microbes paint plastic shiny.", "They decompose it.", "That's it — microbes break it down."),
    ("Why is a banana peel biodegradable but a polythene bag often not?", "Peel is food for microbes; many plastics aren't usable that way?", "Natural vs synthetic. Difference?", "Stay on this.", "Bags are bananas in disguise.", "One is microbial food; the other isn't.", "That's it — microbes can eat the peel, not the bag."),
    ("Does 'natural' always mean biodegradable fast?", "Usually more likely, but the chapter cares about whether microbes can process it?", "Wood vs some naturals that last. Nuance?", "Don't over-simplify?", "Everything natural vanishes in a minute.", "The test is decomposition, not the label 'natural'.", "That's it — the test is whether it breaks down."),
])

add("Digestion and enzymes", [
    ("What is digestion?", "Breaking food into small soluble molecules the body can absorb?", "Big meal to tiny bits. Digestion?", "Stay on this, not on plants' photosynthesis.", "Digestion is a type of current.", "Breaking food so it can be absorbed.", "That's it — digestion is that breakdown."),
    ("What is an enzyme here?", "A biological catalyst that speeds a digestion step?", "Amylase on starch. Helper?", "Not used up as food itself in the school line?", "Enzymes are bits of metal from the pan.", "A biological catalyst for a reaction.", "That's it — enzyme is that helper catalyst."),
    ("What does amylase do, school-level?", "Breaks starch toward sugars?", "Saliva. Starch?", "Stay on digestion.", "Amylase melts bones.", "It acts on starch.", "That's it — amylase vs starch."),
    ("Why chew besides manners?", "Smaller pieces, more surface, easier enzyme attack?", "Teeth. Surface area?", "Stay on this.", "Chewing adds extra vitamins from air.", "More surface for enzymes.", "That's it — chewing helps enzymes reach food."),
    ("Where is food mainly absorbed, school picture?", "Small intestine?", "Not the stomach as the main absorb site?", "Stay on this.", "Food is absorbed in the hair.", "The small intestine.", "That's it — absorption mainly in the small intestine."),
    ("What is a catalyst, loosely?", "Speeds a reaction without being the fuel?", "Helper. Catalyst?", "Enzymes are bio-catalysts?", "A catalyst is the food itself.", "It speeds without being the meal.", "That's it — catalyst speeds the change."),
    ("Why is the stomach acidic in the school story?", "Helps some enzymes (pepsin) and can deter some microbes?", "Acid. Stomach?", "Stay on digestion.", "Stomach acid is for photosynthesis.", "Acid conditions for those enzymes / defence.", "That's it — acid helps that stage."),
    ("Is digestion the same as respiration?", "No — digestion prepares food; respiration releases energy from it in cells?", "Two life processes. Unmix?", "Stay on this.", "They are the same word.", "No — breakdown for absorb vs energy in cells.", "That's it — you unmixed digestion and respiration."),
    ("What is peristalsis, loosely?", "Muscle waves that push food along?", "Gullet. Push?", "Not an enzyme name?", "Peristalsis is a type of light.", "Waves that move food along.", "That's it — peristalsis is the push along."),
    ("Why enzymes have an 'optimum' in school graphs?", "Too cold slow; too hot can destroy the enzyme (denature)?", "Temperature. Peak?", "Stay on enzymes.", "Enzymes work only at absolute zero.", "A best-condition peak; heat can wreck them.", "That's it — optimum, and heat can denature."),
])

add("Atmospheric pressure and altitude", [
    ("What is atmospheric pressure?", "The pressure from the weight of air above you?", "Air has weight. Press?", "Stay on this, not on sound.", "Atmospheric pressure is a type of hormone.", "Pressure due to the air above.", "That's it — that's atmospheric pressure."),
    ("Why is pressure lower on a mountain?", "Less air above you?", "High altitude. Thinner pile?", "Stay on this.", "Mountains add extra air always.", "A shorter column of air above.", "That's it — less air above, lower P."),
    ("Why do ears 'pop' sometimes when you climb?", "Pressure outside changing vs inside the ear?", "Altitude change. Ears?", "Stay on air pressure.", "Ears pop from magnetism.", "Outside pressure change.", "That's it — a pressure mismatch in the ear."),
    ("What does a barometer measure, school?", "Atmospheric pressure?", "Mercury/aneroid. Barometer?", "Not temperature as the main?", "Barometers measure pH.", "Air pressure.", "That's it — barometer is air pressure."),
    ("Why is it harder to breathe at high altitude, loosely?", "Thinner air, less oxygen per lungful?", "Mountain. Oxygen?", "Linked to lower pressure/density?", "There is more oxygen on peaks always.", "Less oxygen in each breath.", "That's it — thinner air, less oxygen."),
    ("Does air press only downward?", "As a fluid, it presses on all surfaces, including sideways?", "Atmosphere as a fluid. All around?", "Stay on this.", "Air only sits on your head.", "It presses in all directions.", "That's it — air pressure is all around."),
    ("Why a suction cup sticks, loosely?", "Lower pressure inside than outside air pushing?", "Cup on tile. Outside air?", "Stay on atmospheric pressure.", "Suction cups use glue from trees only.", "Outside air pressure holds it.", "That's it — outside air pushes it on."),
    ("What happens to boiling point at altitude, school?", "Water can boil at a lower temperature when P is lower?", "Mountain cooking. Boil?", "Stay on this.", "Water needs higher T always on mountains.", "Lower pressure, lower boiling point.", "That's it — lower P, easier boil."),
    ("Is atmospheric pressure the same as wind?", "Wind is air moving; pressure is the push of the air, even in still air?", "Unmix. Still day still has P?", "Stay on this.", "No pressure exists without a gale.", "Pressure is there even if air is still.", "That's it — still air still presses."),
    ("Why vacuum packing, loosely?", "Remove air so outside pressure / less oxygen affects the contents?", "Bag clings. Outside P?", "Don't overclaim food chemistry?", "Vacuum packing adds extra air.", "Less inside air / outside pressure effect.", "That's it — you changed the air inside."),
])
