"""More v9 extras."""

from v9_extra_rest import add

add("Puberty and reproductive maturity", [
    ("What is puberty?", "The time when the body becomes able to reproduce, with hormone-driven changes?", "Teen changes. Reproductive ability?", "Not a type of bone disease?", "Puberty means learning maths.", "The start of reproductive maturity plus those changes.", "That's it — puberty is that maturing phase."),
    ("Which hormones are the school stars here?", "Oestrogen and testosterone among others, from gonads?", "Ovaries/testes. Chemicals?", "Stay on this topic.", "Puberty is caused by magnets.", "Sex hormones from the gonads.", "That's it — gonadal hormones drive much of it."),
    ("What is a secondary sexual characteristic?", "A feature of puberty that isn't the gamete-making itself, like hair or voice?", "Voice break, breasts. Secondary?", "Not the gametes themselves?", "It means a second skeleton.", "Body features that appear at puberty.", "That's it — those are secondary characteristics."),
    ("Why do periods start around puberty?", "The uterus cycling in a body that can now support a pregnancy in principle?", "Menstrual cycle begins. Link?", "Stay age-appropriate Grade 10.", "Periods are caused by eating iron nails.", "The cycle starts as reproductive maturity arrives.", "That's it — cycles begin with that maturity."),
    ("Is everyone the same age at puberty?", "No — a range is normal, driven by hormones and individuals?", "Some earlier, some later. Range?", "Not a race?", "Everyone starts on the same calendar day.", "Timing varies.", "That's it — age varies."),
    ("What is reproductive maturity?", "Being able to produce mature gametes / reproduce?", "Sperm or eggs possible. Mature?", "Related to puberty?", "It means they can drive a car.", "Ability to reproduce / make mature gametes.", "That's it — that's reproductive maturity."),
    ("Why is the pituitary involved?", "It can signal the gonads with hormones?", "Master gland again. Signal?", "Chain of command?", "The pituitary stores urine at puberty.", "It signals the sex glands.", "That's it — pituitary talks to gonads."),
    ("Are puberty changes only physical?", "Mainly taught as physical/hormonal; feelings also shift, but stay on science?", "Body plus mood sometimes. Still hormones?", "Don't moralize?", "Puberty is only a haircut.", "Physical/hormonal changes are the science core.", "That's it — hormones change the body."),
    ("What are testes and ovaries doing more of at puberty?", "Making more sex hormones and maturing gamete production?", "Gonads wake up. Job?", "Stay on this.", "They become kidneys.", "Hormone and gamete activity ramps up.", "That's it — gonads step up."),
    ("Is puberty the same as fertilization?", "No — puberty is becoming able; fertilization is gametes fusing?", "Two ideas. Unmix?", "One is a life stage, one is an event?", "They are the same word.", "No — maturing vs fusion.", "That's it — you unmixed puberty and fertilization."),
])

add("Reaction of acids with metals", [
    ("What gas do many acids make with reactive metals?", "Hydrogen?", "Pop test. Which gas?", "Stay on acid + metal.", "They make oxygen that pops.", "Hydrogen.", "That's it — hydrogen is the gas."),
    ("What else often forms besides the gas?", "A salt?", "Acid + metal → salt + hydrogen. Family?", "Not a type of light?", "They form only water always, no salt.", "A salt.", "That's it — salt plus hydrogen."),
    ("How do we test hydrogen in school?", "A burning splint gives a pop?", "Pop test. Hydrogen?", "Not limewater?", "Hydrogen turns limewater milky.", "The pop with a lighted splint.", "That's it — pop test for hydrogen."),
    ("Does every metal behave the same?", "Less reactive metals may barely react?", "Copper vs magnesium. Different?", "Reactivity series later?", "All metals explode identically in acid.", "No — reactivity differs.", "That's it — metals differ."),
    ("Is this the same as acid + base?", "No — metal reaction makes hydrogen; neutralization makes water (and salt)?", "Two families. Unmix?", "Stay on chemistry.", "They are identical reactions.", "No — different reaction families.", "That's it — you unmixed metal vs base."),
    ("What does 'reactive metal' mean here?", "A metal that more readily displaces hydrogen from the acid?", "Mg vs Cu. Who fizzes?", "Not a personality?", "Reactive means the metal is wet.", "It fizzes / displaces hydrogen more readily.", "That's it — reactive means it reacts more readily."),
    ("Why wear goggles for this demo?", "Acid and possibly flammable hydrogen?", "Safety. Eyes?", "Not because metals are loud only?", "Goggles heat the acid.", "To protect eyes from acid (and care with gas).", "That's it — safety from acid."),
    ("What is a salt in this reaction?", "The ionic product named from metal + acid residue?", "Magnesium chloride as an example. Salt?", "Not only table salt?", "Salt means only NaCl from the sea.", "The metal-acid product compound.", "That's it — that product is a salt."),
    ("Does gold typically fizz in dilute acid like this?", "Usually no — too unreactive in the school picture?", "Jewellery. Fizz?", "Reactivity series?", "Gold always dissolves in lemon juice instantly.", "Typically no obvious reaction.", "That's it — gold is too unreactive here."),
    ("What is the word equation pattern?", "Metal + acid → salt + hydrogen?", "Pattern. Words?", "Stay on this family.", "Metal + acid → oxygen + plastic.", "Salt plus hydrogen.", "That's it — that's the pattern."),
])

add("Water of crystallization", [
    ("What is water of crystallization?", "Water bound in a crystal structure of some salts?", "Blue copper sulfate. Water in the crystal?", "Not puddles on the bench?", "It is water you drink from a tap inside atoms of gold.", "Water locked in the crystal.", "That's it — that's water of crystallization."),
    ("What happens when you heat blue copper sulfate gently, school demo?", "It can go white as water leaves?", "Colour change. Water off?", "Hydrated vs anhydrous?", "Heating paints it with chlorophyll.", "It can lose water and look white/pale.", "That's it — heating drives water off."),
    ("What does anhydrous mean here?", "Without that water of crystallization?", "Opposite of hydrated. Dry form?", "Not a type of acid?", "Anhydrous means extra wet.", "Without the crystal water.", "That's it — anhydrous is the dry form."),
    ("What does hydrated mean here?", "The salt includes water of crystallization?", "Blue crystals. Hydrated?", "Opposite of anhydrous?", "Hydrated means the salt is a gas.", "It contains that crystal water.", "That's it — hydrated includes the water."),
    ("Can adding water reverse the copper sulfate colour in the demo?", "The white form can go blue again if water returns?", "Rehydration. Colour back?", "Stay on this salt.", "Water never interacts with it.", "Yes — water can restore the blue hydrated form.", "That's it — water brings the blue back."),
    ("Is this the same as a solution?", "No — crystal water is in the solid lattice, not a beaker of solution?", "Solid crystals vs dissolved. Unmix?", "Stay on this.", "They are identical.", "No — lattice water vs a solution.", "That's it — you unmixed crystal water and a solution."),
    ("Why do some crystals look wet-named but feel dry?", "The water is part of the structure, not loose liquid?", "Dry-looking blue crystals. Still 'water of'?", "Not dripping?", "They are secretly lakes.", "The water is bound, not a puddle.", "That's it — bound water, not a puddle."),
    ("What is a hydrated salt, in one line?", "A salt whose formula includes water of crystallization?", "CuSO4·5H2O idea. Formula water?", "School formula?", "It means the salt is an animal.", "A salt with formula water in the crystal.", "That's it — that's a hydrated salt."),
    ("Does heating always destroy the metal in that demo?", "The idea is losing water, not burning the copper away?", "Gentle heat. Water off, salt still there?", "Don't jump to combustion?", "The copper vanishes into light.", "Water leaves; the salt can remain.", "That's it — water leaves, salt can stay."),
    ("Why mention it in acids-and-salts chapters?", "Many salts from those reactions can be hydrated crystals?", "Crystals from solutions. Water in them?", "Stay on salts.", "It is only about the sky.", "Salts often crystallise with that water.", "That's it — it's a salt-crystal idea."),
])

add("Covalent bonding in carbon compounds", [
    ("What is a covalent bond, school-level?", "Sharing a pair of electrons between atoms?", "Not steal-and-stick like ionic. Share?", "Stay on carbon compounds.", "Covalent means a magnet between desks.", "A shared pair of electrons.", "That's it — covalent is sharing."),
    ("Why does carbon form covalent compounds so much?", "Four outer electrons, needs four shares, makes chains and rings?", "Carbon's four arms. Networks of share?", "Not because carbon is a metal ion typically here?", "Carbon only makes ionic tablesalt.", "It shares to make four bonds, and can chain.", "That's it — carbon shares and chains."),
    ("What is a molecule here?", "A group of atoms held by covalent bonds?", "CH4 as a unit. Molecule?", "Not a giant ionic lattice like NaCl?", "A molecule is a type of current.", "Atoms covalently bound as a unit.", "That's it — that's a molecule."),
    ("Why don't typical covalent organics conduct as solids?", "No free ions or delocalised electrons in simple molecules?", "Sugar vs salt solution. Conduct?", "Stay on bonding.", "They are the best wires.", "Simple molecules don't provide mobile charge.", "That's it — no mobile charge, no conduction."),
    ("What is a single covalent bond?", "One shared pair?", "Line in a displayed formula. One pair?", "Not a triple?", "A single bond is three magnets.", "One shared pair.", "That's it — single means one pair."),
    ("What is a double bond, loosely?", "Two shared pairs, like in O=C=O or C=C?", "Two lines. Two pairs?", "Stay on carbon compounds.", "Double bond means two ionic charges only.", "Two shared pairs.", "That's it — double is two pairs."),
    ("Is methane ionic?", "No — C and H share in CH4?", "Hydrocarbon. Share?", "Don't treat it as NaCl?", "Methane is table salt.", "It's covalent.", "That's it — methane is covalent."),
    ("What does a displayed formula show?", "How atoms are bonded, not only the count?", "Lines between atoms. Picture?", "Different from a molecular formula?", "It shows the price of the chemical.", "The bonding arrangement.", "That's it — it shows the bonds."),
    ("Why can carbon make long chains?", "It can bond to other carbons strongly in a row?", "C-C-C. Backbone?", "That's organic chemistry's door?", "Carbon never bonds to carbon.", "Carbon-carbon bonds make chains.", "That's it — C–C chaining."),
    ("Are covalent bonds only in carbon?", "No — H2, O2, H2O are covalent too, but carbon is the chain-maker here?", "Other examples. Still share?", "This chapter focuses carbon?", "Only carbon in the universe shares.", "Sharing exists beyond carbon; carbon chains are special here.", "That's it — covalent is wider; carbon chains are the focus."),
])

add("Functional groups", [
    ("What is a functional group?", "An atom or group that gives a family its typical reactions?", "–OH on alcohols. Badge?", "Stay on carbon compounds.", "A functional group is a type of magnet.", "The reactive badge of the family.", "That's it — that's a functional group."),
    ("What is an alcohol's typical group in school?", "The –OH (hydroxyl) group?", "Ethanol. –OH?", "Not a carboxylic –COOH yet?", "Alcohols are only metals.", "The –OH group.", "That's it — alcohols have –OH."),
    ("What is a carboxylic acid's group?", "–COOH?", "Ethanoic acid. –COOH?", "Sour vinegar family?", "Carboxylic acids are only bases.", "The –COOH group.", "That's it — carboxylic acids have –COOH."),
    ("What does the halo-alkane idea add?", "A halogen attached to the carbon chain?", "Chloro- compounds. Halogen?", "Stay on functional groups.", "Halogens are types of food chains.", "A halogen on the chain.", "That's it — that's the halo group idea."),
    ("Why group compounds by functional group?", "Same badge, similar reactions, even if chains differ?", "Family resemblance. Why classify?", "Not by colour of the bottle only?", "Families are random names.", "Similar chemistry from the same badge.", "That's it — the badge predicts reactions."),
    ("Is the carbon chain itself the functional group?", "The chain is the backbone; the group is the special bit?", "Alkane vs alcohol. Difference?", "Unmix chain and badge?", "The chain is always –COOH.", "No — chain vs the reactive group.", "That's it — you unmixed chain and group."),
    ("What is an alkene's functional feature?", "A C=C double bond?", "Unsaturated. Double?", "Not –OH?", "Alkenes are ionic salts.", "The C=C double bond.", "That's it — alkene means C=C."),
    ("Can a molecule have more than one kind of group?", "Yes in more complex molecules, but school starts with one main badge?", "Later organic. Possible?", "Keep Grade 10 simple?", "Impossible forever.", "Possible, but we start with one family badge.", "That's it — one badge first, more later."),
    ("What is a homologous series link?", "Same functional group, chain length stepping by CH2?", "Family plus chain growth. Link?", "Stay on this.", "Homologous means random.", "Same group, chain grows by CH2.", "That's it — that's the link."),
    ("Does the functional group change the compound's name family?", "Yes — -ol, -oic acid, etc., in school naming?", "Ending of the name. Clue?", "Name as a hint?", "Names are unrelated to groups.", "The name family follows the group.", "That's it — names flag the group."),
])

add("Balancing chemical equations", [
    ("Why balance an equation?", "Atoms aren't created or destroyed, so both sides need the same counts?", "Conservation. Same atoms?", "Not to make it look pretty only?", "We balance to change the products into gold.", "So atom counts match.", "That's it — balancing respects conservation."),
    ("What can you change when balancing?", "Coefficients (big numbers in front), not the little formulas themselves?", "2H2 not H3. What is legal?", "Don't rewrite H2O as H3O to force it?", "You change subscripts freely.", "The numbers in front.", "That's it — change coefficients, not formulas."),
    ("What is a coefficient?", "The number of those units in the equation?", "2H2 means two molecules. Coefficient?", "Not the subscript inside H2?", "A coefficient is a type of acid.", "The multiplier in front.", "That's it — coefficient is the front number."),
    ("What is a subscript in H2?", "How many of that atom are in one molecule?", "H2 vs 2H. Different?", "Don't mix with the front 2?", "Subscript means temperature.", "Atoms inside one formula unit.", "That's it — subscript is inside the formula."),
    ("How do you know it's balanced?", "Each element has the same number of atoms on both sides?", "Count C, H, O. Match?", "Stay on counting.", "It's balanced if it looks short.", "Matching atom counts per element.", "That's it — count until they match."),
    ("Why not balance by inventing new products?", "The reaction's products are given; we only count them fairly?", "Don't add extra mystery chemicals?", "Stay on the given reaction?", "You may invent any product you like.", "Keep the real species; only count them.", "That's it — don't invent extra products."),
    ("Is H2 + O2 → H2O already balanced?", "Count H and O — oxygen doesn't match until you use 2H2 + O2 → 2H2O?", "Classic water. Counts?", "Need coefficients?", "It is already perfect as written with one each.", "No — oxygen (and then H) need coefficients.", "That's it — the classic needs 2, 1, 2."),
    ("What does conservation of mass have to do with it?", "If atoms match, mass of atoms matches?", "Same atoms, same mass. Link?", "Not magic mass creation?", "Mass appears from nowhere.", "Balanced atoms mean mass is consistent.", "That's it — that's the mass link."),
    ("Can you balance an ionic equation the same idea?", "Yes — still conserve atoms (and charge, later)?", "Same spirit. Count?", "Grade 10 starts with molecules?", "Ionic equations never need counts.", "Same counting idea.", "That's it — still count."),
    ("What's a first move if it's messy?", "Pick one element that appears in fewest places and fix it, then the rest?", "Strategy. One element first?", "Not random scribbling only?", "Always start by erasing the products.", "Fix one element, then the others.", "That's it — one element at a time."),
])

add("Exothermic and endothermic reactions", [
    ("What is an exothermic reaction?", "One that releases energy to the surroundings, often as heat?", "Hot pack / combustion. Heat out?", "Stay on energy of reaction.", "Exothermic means it absorbs all heat forever.", "Energy released to the surroundings.", "That's it — exo means heat out."),
    ("What is an endothermic reaction?", "One that takes in energy from the surroundings?", "Cold pack. Heat in?", "Opposite of exo?", "Endothermic means it is a type of light.", "Energy taken in.", "That's it — endo means heat in."),
    ("How can a beaker tell you which?", "Temperature of surroundings up suggests exo; down suggests endo?", "Touch/thermometer. Surroundings?", "Not the name of the chemical?", "Beakers cannot change temperature.", "Surroundings warmer → exo; cooler → endo.", "That's it — the surroundings' temperature is the clue."),
    ("Is combustion typically exo or endo?", "Exothermic — flames heat you?", "Burning. Heat out?", "Stay on this.", "Combustion always cools the room.", "Exothermic.", "That's it — burning is exothermic."),
    ("Does breaking bonds take energy or release it, school story?", "Breaking takes energy; making bonds can release?", "Two steps. Break vs make?", "Overall exo if more released on making?", "Breaking bonds always heats you.", "Breaking takes energy in.", "That's it — you pay energy to break bonds."),
    ("What is a chemical energy change overall?", "The balance of energy in vs out for that reaction?", "Net. Overall?", "That's exo vs endo?", "Energy is unrelated to reactions.", "The net energy to or from surroundings.", "That's it — overall net is the classification."),
    ("Is melting ice a chemical reaction?", "Usually taught as physical change, even if it takes heat?", "State change vs new substance. Unmix?", "Endo physical vs chemical endo?", "Melting always makes a new element.", "Melting is a physical change.", "That's it — melting isn't a new substance."),
    ("Why do some reactions need a spark even if exo?", "Activation energy to start, then they can keep going?", "Match to paper. Kickstart?", "Not because they are endo overall?", "Sparks add extra product atoms.", "A start-up energy bump.", "That's it — activation energy to start."),
    ("Can an endothermic reaction still happen?", "Yes if energy is supplied (heat, light, electrical)?", "Photosynthesis as the big school endo?", "Not impossible?", "Endo reactions are imaginary.", "Yes, if energy is supplied.", "That's it — supply energy and they can go."),
    ("Are exo and endo about acids vs alkalis?", "No — any reaction family can be either depending on energy?", "Unmix with pH?", "Stay on energy.", "Exo means acid; endo means alkali.", "They are energy labels, not acid/base.", "That's it — energy, not pH."),
])
