"""More v9 extras."""

from v9_extra_rest import add

add("Saturated vs unsaturated hydrocarbons", [
    ("What is a saturated hydrocarbon?", "Only single C–C bonds, max hydrogens, alkanes?", "No C=C. Saturated?", "Stay on this.", "Saturated means dissolved sugar in petrol.", "Single bonds only / alkane type.", "That's it — saturated means no C=C."),
    ("What is an unsaturated hydrocarbon?", "Has C=C or C≡C, can add more atoms?", "Alkenes/alkynes. Unsaturated?", "Opposite of alkane?", "Unsaturated means wet carbon.", "Contains multiple C–C bonds.", "That's it — unsaturated has double/triple C–C."),
    ("How does bromine water tell them apart in school?", "Unsaturated can decolourise bromine; saturated generally doesn't?", "Orange to colourless. Test?", "Stay on hydrocarbons.", "Bromine water tests pH.", "Decolourising suggests unsaturated.", "That's it — bromine test for unsaturation."),
    ("What is addition across a double bond, loosely?", "Atoms add to C=C, turning it toward single?", "H2 or Br2 adding. Addition?", "Typical of unsaturated?", "Addition means subtracting carbon.", "Atoms add at the double bond.", "That's it — addition at C=C."),
    ("Are alkanes generally more sluggish?", "Yes — substitution rather than easy addition, in school?", "Less reactive. Saturated?", "Don't overclaim never react?", "Alkanes explode if you look at them.", "They don't add like alkenes.", "That's it — alkanes aren't addition-hungry."),
    ("What does C=C mean for the formula vs alkane?", "Fewer hydrogens than CnH2n+2, e.g. CnH2n for a simple alkene?", "Count H. Fewer?", "Stay on this.", "Alkenes have more H than alkanes always.", "Fewer H than the alkane.", "That's it — unsaturation means fewer H."),
    ("Is cooking oil's 'unsaturated' the same word family?", "Same idea: C=C in long chains, loosely?", "Food labels. Related?", "Don't go deep into nutrition science?", "Food unsaturated means no carbon.", "Yes — C=C in those chains too.", "That's it — same unsaturation idea."),
    ("What is an alkyne, school-level?", "A hydrocarbon with a C≡C triple bond?", "Ethyne. Triple?", "Still unsaturated?", "Alkynes are ionic salts.", "A triple-bonded hydrocarbon.", "That's it — alkyne means C≡C."),
    ("Can a molecule be saturated and still be a compound?", "Yes — alkanes are compounds that are saturated?", "Not 'dissolved'. Hydrocarbon meaning?", "Unmix with solutions?", "Saturated only means a solution.", "Yes — saturated hydrocarbons are compounds.", "That's it — saturated isn't only solutions."),
    ("Why care about the difference?", "Different reactions, tests, and uses (plastics from alkenes)?", "Why teach it. Practical?", "Stay on this chapter.", "There is no difference that matters.", "Different bonding, different chemistry.", "That's it — the difference is the chemistry."),
])

add("Binary data representation", [
    ("What is binary, in this chapter?", "A two-symbol system, 0 and 1, for data in computers?", "On/off. Binary?", "Stay on this, not on biology.", "Binary is a type of acid.", "Data as 0s and 1s.", "That's it — binary is 0 and 1."),
    ("Why computers like two states?", "Easy hardware: on/off, high/low?", "Switch. Two levels?", "Not ten fingers inside the chip?", "Chips count in Roman numerals.", "Two electrical states are simple and reliable.", "That's it — two states match hardware."),
    ("What is a bit?", "One binary digit, 0 or 1?", "Smallest piece. Bit?", "Not a type of atom?", "A bit is a type of cell.", "One 0 or 1.", "That's it — a bit is one binary digit."),
    ("What is a byte, school-level?", "A group of 8 bits, often?", "Eight. Byte?", "Enough for many character codes?", "A byte is a type of plant.", "Eight bits (commonly).", "That's it — byte is eight bits."),
    ("How do we store a number like 5 in binary, idea?", "Powers of two: 4+1 → 101?", "Place values 4,2,1. Five?", "Not decimal columns of 10s only?", "5 in binary is 5.", "As a sum of powers of two.", "That's it — binary place values are powers of two."),
    ("What does 0 vs 1 mean physically, loosely?", "Two distinguishable states, not the digits painted?", "Voltage high/low. Meaning?", "Stay on representation.", "0 and 1 are two chemicals in a beaker only.", "Two physical states standing for the symbols.", "That's it — physical states encode 0 and 1."),
    ("Can text be binary too?", "Yes — codes map letters to bit patterns?", "A as a number, then binary. Text?", "Not only maths class numbers?", "Text cannot be stored.", "Letters get bit-pattern codes.", "That's it — text is coded into bits."),
    ("Is binary the same as Boolean true/false, loosely?", "Related idea of two values; bits can flag true/false?", "Two-valued. Link?", "Don't over-merge all CS?", "Binary is a type of hormone.", "Two-valued, like true/false flags.", "That's it — two values, related idea."),
    ("Why not store everything as decimal digits in hardware?", "Ten precise levels are harder than two clean levels?", "Noise. Two is robust?", "That's the engineering reason?", "Decimal is easier inside every chip always.", "Two levels are cleaner to build.", "That's it — two levels beat ten in hardware."),
    ("What is digital, in one line here?", "Information as discrete bits rather than a smooth voltage drawing?", "Digital vs analogue loosely. Discrete?", "Stay on representation.", "Digital means fingers only.", "Discrete 0/1 (or coded) values.", "That's it — digital is discrete coded data."),
])

add("Electromagnetic induction", [
    ("What is electromagnetic induction?", "Making a current (or emf) by changing magnetic field through a coil?", "Move magnet in coil. Current?", "Stay on this.", "Induction is a plant tropism.", "A changing field through a coil can make current.", "That's it — that's induction."),
    ("What do you need to induce a current in a closed coil?", "A changing flux — move magnet, move coil, or change I in a neighbour?", "Change. Not a still magnet in a still coil?", "Stay on this.", "A still magnet in a still coil always drives huge current.", "A change in the magnetic field through it.", "That's it — change is required."),
    ("What is Faraday's idea, school-level?", "Induced emf related to how fast the flux changes?", "Faster motion, bigger effect? Rate?", "Stay on induction.", "Faraday said magnets eat current.", "Faster change, larger induced emf.", "That's it — rate of change matters."),
    ("What is a generator's school idea?", "Turn a coil in a field (or field past a coil) to induce current?", "Bike dynamo. Rotation?", "That's induction in a machine?", "Generators store sugar.", "Motion plus field → induced current.", "That's it — a generator uses induction."),
    ("Does a steady field through a still coil induce current?", "No — no change, no induced current in the school rule?", "Still bar magnet inside. Current?", "Change needed?", "Steady field always induces more.", "No change, no induced current.", "That's it — steady and still isn't enough."),
    ("What is Lenz's law pointing at, loosely?", "The induced current fights the change that caused it?", "Opposition. Lenz?", "Don't need full calculus?", "Lenz's law is about acids.", "Induced effects oppose the change.", "That's it — opposition to the change."),
    ("Can a changing current in one coil affect another?", "Yes — transformer idea: changing I, changing field, induced in the other?", "Two coils. Mutual?", "Stay on induction.", "Coils never affect each other.", "Yes — a changing current can induce in a neighbour.", "That's it — that's the transformer seed."),
    ("Why move the magnet faster in a demo?", "Larger rate of change, bigger induced current (meter flicks more)?", "Speed. Flick?", "Stay on this.", "Faster motion always kills the field.", "Faster change, bigger induced effect.", "That's it — faster gives a bigger flick."),
    ("Is induction the same as an electromagnet?", "Electromagnet: current makes field. Induction: changing field makes current?", "Reverse jobs. Unmix?", "Stay on this.", "They are the same word.", "No — opposite directions of the idea.", "That's it — you unmixed them."),
    ("What is flux, loosely in school?", "How much field 'goes through' the coil's face?", "Field through area. Flux?", "Change of that induces?", "Flux is a type of water only.", "Field through the coil's area.", "That's it — flux is field through the loop."),
])

add("Magnetic field around a current-carrying conductor", [
    ("Does a current make a magnetic field?", "Yes — a wire with current has a field around it?", "Compass near a wire. Deflect?", "Stay on this.", "Current never makes a field.", "Yes — current produces a magnetic field.", "That's it — current makes a field."),
    ("What is the pattern around a straight wire, school?", "Circles around the wire?", "Iron filings / compasses. Circles?", "Right-hand grip?", "The field is a straight arrow only along the wire always.", "Circular around the wire.", "That's it — circular field around a straight wire."),
    ("What is the right-hand grip rule for?", "Thumb in current direction, fingers show field circles?", "Grip. Direction?", "Stay on this.", "The left foot shows current.", "Relating I direction to field direction.", "That's it — grip maps I to field."),
    ("What if current is reversed?", "Field circles reverse?", "Compass flips. Reverse I?", "Stay on this.", "Reverse current leaves the field identical.", "The field direction reverses.", "That's it — reverse I, reverse field."),
    ("Is this field the same as a bar magnet's shape?", "Different pattern for a single wire; a coil can look bar-like?", "Straight wire vs solenoid. Different maps?", "Don't force one picture?", "Every field is a bar magnet drawing.", "A straight wire is circular, not bar-shaped.", "That's it — wire vs bar have different maps."),
    ("What happens if I is zero?", "Field from that current disappears?", "Switch off. Compass back?", "Stay on this.", "The field stays forever.", "No current, no that field.", "That's it — no I, no current-field."),
    ("Why compasses in Oersted's story moved?", "They detected the wire's magnetic field?", "Historic demo. Compass?", "Stay on current and magnetism.", "Compasses detect pH.", "The current's field nudged them.", "That's it — Oersted's compasses felt the wire's field."),
    ("Does a stronger current make a stronger field, school?", "Yes — field around the wire increases with I?", "More I, more effect on compass?", "Stay on this.", "More current always kills magnetism.", "Stronger I, stronger field.", "That's it — field grows with current."),
    ("Can two wires with current affect each other?", "Yes — each sits in the other's field (forces between wires)?", "Later: motors. Two wires?", "Don't need full ampère law?", "Wires never feel magnetism.", "Yes — current-fields can push wires.", "That's it — currents can magnetically push."),
    ("Is the field a material coming out of the copper?", "It's a field in the space around, not copper powder spraying?", "Invisible influence. Field?", "Stay conceptual Grade 10.", "Copper dust is the field.", "A magnetic field in the surrounding space.", "That's it — a field around, not copper spray."),
])

add("Ionic bond formation", [
    ("What is an ionic bond?", "Attraction after electrons transfer, making + and − ions?", "NaCl story. Transfer then stick?", "Stay on this.", "Ionic bond is a shared pair only always.", "Transfer of electrons, then opposite ions attract.", "That's it — ionic is transfer plus attraction."),
    ("What does sodium do in the NaCl school picture?", "Lose one electron to form Na+?", "Metal. Lose e−?", "Not gain two?", "Sodium gains seven electrons here.", "It loses one electron.", "That's it — Na loses one."),
    ("What does chlorine do in that picture?", "Gain one electron to form Cl−?", "Non-metal. Gain?", "Complete the outer shell story?", "Chlorine loses seven here.", "It gains one electron.", "That's it — Cl gains one."),
    ("Why do the ions stick?", "Opposite charges attract?", "Plus and minus. Stick?", "Not a covalent share as the main NaCl story?", "They stick with gravity only.", "Electrostatic attraction.", "That's it — opposite charges attract."),
    ("What is a lattice here?", "A giant regular stack of ions, not a single NaCl molecule?", "Crystal. Lattice?", "Don't draw one pair as the whole crystal?", "NaCl is a tiny two-atom gas molecule only.", "A giant ionic structure.", "That's it — a lattice of ions."),
    ("Why do ionic solids often not conduct, but melts/solutions can?", "Ions must be free to move to carry current?", "Solid vs molten. Mobile ions?", "Stay on bonding/electricity link.", "Solid salt is the best wire always.", "Mobile ions conduct; locked ions don't.", "That's it — mobile ions are needed."),
    ("Is this the same as covalent sharing?", "No — transfer vs share?", "NaCl vs CH4. Unmix?", "Stay on this.", "They are identical.", "No — transfer vs share.", "That's it — you unmixed ionic and covalent."),
    ("What is an ion?", "An atom (or group) with a charge after losing/gaining electrons?", "Na+, Cl−. Charged?", "Not a neutral atom?", "An ion is a type of wave.", "A charged particle from electron change.", "That's it — ion means charged."),
    ("Why metals with non-metals often go ionic in school?", "Metals tend to lose, non-metals gain, toward full shells?", "Left–right of table. Transfer?", "Not always, but the Grade-10 pattern?", "Metals share with metals as NaCl.", "Lose-and-gain pairs well.", "That's it — metal + non-metal often transfer."),
    ("What is a formula unit of NaCl, loosely?", "The ratio 1:1 in the lattice, not a separate molecule?", "NaCl as a ratio. Formula?", "Stay on ionic compounds.", "NaCl means nine chlorines.", "The simplest ion ratio.", "That's it — formula is the ratio."),
])

add("Physical properties: malleability and ductility", [
    ("What is malleability?", "Can be hammered into sheets?", "Gold leaf. Hammer?", "Stay on metals.", "Malleability is a type of current.", "Can be beaten into sheets.", "That's it — malleable means sheet-able."),
    ("What is ductility?", "Can be drawn into wires?", "Copper wire. Pull?", "Different from malleable?", "Ductility is a type of acid.", "Can be drawn into wires.", "That's it — ductile means wire-able."),
    ("Why do metals often show both, school story?", "Layers of ions/atoms can slide, metallic bonding?", "Sea of electrons loosely. Slide?", "Not because metals are liquids at room T usually?", "Metals flow because they are gases.", "Metallic structure lets layers slide.", "That's it — sliding layers, metallic bond."),
    ("Is glass ductile like copper?", "No — it tends to shatter, not draw to wire?", "Brittle vs ductile. Contrast?", "Stay on properties.", "Glass is the best wire metal.", "Glass is brittle, not ductile like copper.", "That's it — glass isn't metal-ductile."),
    ("Why is copper used for wires besides conduction?", "It's ductile, so it can be drawn thin?", "Two reasons: conducts and draws. Ductile?", "Stay on this.", "Copper wires are ductile because they are wooden.", "Ductility lets us make wire.", "That's it — ductile copper becomes wire."),
    ("Why is aluminium used in foil?", "Malleable enough to roll thin?", "Foil. Sheets?", "Stay on malleability.", "Foil is ductility only, never sheets.", "Malleability lets us make foil.", "That's it — malleable metal becomes foil."),
    ("Are malleable and ductile the same word?", "Both are deforming without snapping, but sheet vs wire?", "Unmix with an example each?", "Stay on this.", "They are identical words.", "No — sheets vs wires.", "That's it — you unmixed them."),
    ("Do ionic crystals hammer into sheets easily?", "They tend to shatter along planes, not like metals?", "Salt crystal. Brittle?", "Contrast metallic?", "Salt is the most malleable metal.", "Ionic solids are typically brittle.", "That's it — ionic is brittle, not malleable like metal."),
    ("Is hardness the same as malleability?", "Hard can still be brittle; malleable is about shaping?", "Diamond vs gold. Different ideas?", "Unmix?", "Hardness equals malleability.", "No — hard isn't the same as malleable.", "That's it — different properties."),
    ("What property lets gold become leaf?", "High malleability?", "Very thin sheet. Gold?", "Stay on this.", "Gold leaf is a plant leaf.", "Malleability.", "That's it — gold is extremely malleable."),
])
